=== sillsdev/paws/src/org/sil/paws/resources/configuration/Data/PAWSSKWriterDescription.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--DTD generated by XML Spy v3.5 (http://www.xmlspy.com)-->
<!-- DTD for PAWS Starter Kit Writer Page Description  -->
<!-- Entity definitions -->
<!ENTITY % chunk "p | example | table | tablenumbered | ol | ul | dl">
<!ENTITY % embedded "case | text | langData | langName | gloss | exampleRef | sectionRef | appendixRef | comment | object | br | category | feature | img | translatorInstruction | citation | endnote | contentCheckBoxOther">
<!ENTITY nbsp "&#160;">
<!ELEMENT and EMPTY>
<!ELEMENT appendix (secTitle, (%chunk; | section1 | section2)*)>
<!ATTLIST appendix
	id ID #REQUIRED
	label CDATA #IMPLIED
>
<!ELEMENT appendixRef EMPTY>
<!ATTLIST appendixRef
	app IDREF #REQUIRED
>
<!ELEMENT br EMPTY>
<!ELEMENT caption (content | %embedded;)*>
<!-- content -->
<!ELEMENT case (caseText*)>
<!ATTLIST case
  element CDATA #REQUIRED
  attr CDATA #REQUIRED
>
<!ELEMENT caseText (#PCDATA|case)*>
<!ATTLIST caseText
  value CDATA #REQUIRED
>
<!ELEMENT category (#PCDATA)>
<!-- content is the name of the syntactic category -->
<!ELEMENT citation EMPTY>
<!ATTLIST citation
    ref IDREF #REQUIRED
    page CDATA #IMPLIED
    author (yes | no) "yes"
    paren (both | none | initial | final) #IMPLIED
>
<!ELEMENT col (content | langData | gloss | case)*>
<!-- the content of rowspan actually gets calculated ono the fly; so just use any number in the description page -->
<!ATTLIST col
	align (left | center | right | justify) "left"
  class CDATA #IMPLIED
  show IDREF #IMPLIED
  exampleLoc CDATA #IMPLIED
  colspan CDATA #IMPLIED
  rowspan CDATA #IMPLIED
 >
<!-- comments are for the author.  The intent is that they will not show up in
	 the formatted version of the paper. -->
<!ELEMENT comment (#PCDATA | %embedded;)*>
<!ELEMENT content (#PCDATA)>
<!ELEMENT contentCheckBoxOther EMPTY>
<!ATTLIST contentCheckBoxOther
   contentLoc CDATA #REQUIRED
>
<!-- definition description -->
<!ELEMENT dd (content | %embedded; | %chunk;)*>
<!-- content -->
<!ATTLIST dd
  show IDREF #IMPLIED
>
<!-- definition list -->
<!ELEMENT dl (dt | dd)*>
<!ATTLIST dl
  show IDREF #IMPLIED
>
<!-- definition term -->
<!ELEMENT dt (content | %embedded; | %chunk;)*>
<!-- content -->
<!ATTLIST dt
  show IDREF #IMPLIED
>
<!ELEMENT endnote (p)*>
<!ATTLIST endnote
    id ID #REQUIRED
>
<!ELEMENT example (interlinear | table)>
<!ATTLIST example
  num ID #IMPLIED
  show IDREF #IMPLIED
  contentType IDREF #IMPLIED
>
<!-- references to example numbers or example number/letter.
	 Use just num for the example number.
	 Use just letter for an example number/letter combination.
	 One may include parentheses around the date ("both", the default), or
	   one may have no parentheses or just initial or just final.
	 One may append some punctuation (punct) to the end of the number.
	 One may only include the letter (and not the number). -->
<!ELEMENT exampleRef EMPTY>
<!ATTLIST exampleRef
  num CDATA #IMPLIED
  letter CDATA #IMPLIED
  equal (no | yes) "no"
  punct CDATA #IMPLIED
  paren (none | both | initial | final) #IMPLIED
  letterOnly (no | yes) "no"
>
<!ELEMENT feature (#PCDATA)>
<!-- gloss is a way to tag some text as being a gloss in a particular language. -->
<!ELEMENT gloss (content | %embedded;)*>
<!-- content -->
<!ELEMENT headerCol (#PCDATA| langName|object)*>
<!ATTLIST headerCol
	align (left | center | right | justify) "left"
  class CDATA #IMPLIED
  show IDREF #IMPLIED
>
<!ELEMENT headerRow (headerCol+)>
<!ATTLIST headerRow
  class CDATA #IMPLIED
  show IDREF #IMPLIED
>
<!ELEMENT img EMPTY>
<!ATTLIST img
  src CDATA #REQUIRED
>
<!ELEMENT interlinear EMPTY>
<!ATTLIST interlinear
  exampleLoc CDATA #REQUIRED
>
<!-- langData is a way to tag some text as belonging to a particular language. -->
<!ELEMENT langData (#PCDATA)>
<!ATTLIST langData
	lang CDATA #IMPLIED
>
<!-- content -->
<!ELEMENT langName EMPTY>
<!-- object is a generic way to tag a special kind of object.  One can
	 use the CSS stylesheet to format these objects by referring to the
	 class attribute.  -->
<!-- list element -->
<!ELEMENT li (content | %embedded; | %chunk;)*>
<!-- content -->
<!ATTLIST li
  id ID #IMPLIED
  show IDREF #IMPLIED
>
<!ELEMENT object (content | %embedded;)*>
<!-- content -->
<!ATTLIST object
  class CDATA #REQUIRED
>
<!-- ordered list -->
<!ELEMENT ol (li | ol | ul)*>
<!ATTLIST ol
  show IDREF #IMPLIED
>
<!ELEMENT or EMPTY>
<!ELEMENT p (content | %embedded;)*>
<!-- content -->
<!ATTLIST p
  style CDATA #IMPLIED
  show IDREF #IMPLIED
  contentType IDREF #IMPLIED
>
<!ELEMENT portion ((appendix+ |section1+), showWhen*)>
<!ELEMENT row (headerCol?, col+)>
<!ATTLIST row
  class CDATA #IMPLIED
  show IDREF #IMPLIED
>
<!ELEMENT secTitle (#PCDATA | %embedded;)*>
<!ELEMENT section1 (secTitle, (%chunk; | section2)*)>
<!ATTLIST section1
  id ID #REQUIRED
  show IDREF #IMPLIED
>
<!ELEMENT section2 (secTitle, (%chunk; | section3)*)>
<!ATTLIST section2
  id ID #REQUIRED
  show IDREF #IMPLIED
>
<!ELEMENT section3 (secTitle, (%chunk; | section4)*)>
<!ATTLIST section3
  id ID #REQUIRED
  show IDREF #IMPLIED
>
<!ELEMENT section4 (secTitle, (%chunk; | section5)*)>
<!ATTLIST section4
  id ID #REQUIRED
  show IDREF #IMPLIED
>
<!ELEMENT section5 (secTitle, (%chunk; | section6)*)>
<!ATTLIST section5
  id ID #REQUIRED
  show IDREF #IMPLIED
>
<!ELEMENT section6 (secTitle, (%chunk;)*)>
<!ATTLIST section6
  id ID #REQUIRED
  show IDREF #IMPLIED
>
<!-- references to sections, etc. -->
<!ELEMENT sectionRef EMPTY>
<!ATTLIST sectionRef
  sec CDATA #REQUIRED
>
<!ELEMENT showWhen ((whenValue | useShowWhen), ((or | and), (whenValue | useShowWhen))*)>
<!ATTLIST showWhen
  id ID #REQUIRED
>
<!ELEMENT table (caption?, headerRow*, row+)>
<!ATTLIST table
  border CDATA #IMPLIED
  class CDATA #IMPLIED
  show IDREF #IMPLIED
>
<!ELEMENT tablenumbered (table)>
<!ATTLIST tablenumbered
  id ID #IMPLIED
  contentType IDREF #IMPLIED
  show IDREF #IMPLIED
>
<!ELEMENT text (content | %embedded;)*>
<!ATTLIST text
  show IDREF #REQUIRED
>
<!ELEMENT translatorInstruction (#PCDATA)>

<!ELEMENT whenValue EMPTY>
<!ATTLIST whenValue
  element CDATA #REQUIRED
  attr CDATA #IMPLIED
  value CDATA #REQUIRED
  negateValue (yes | no) "no"
>
<!-- unordered list -->
<!ELEMENT ul (li | ol | ul)*>
<!ATTLIST ul
  show IDREF #IMPLIED
  contentType IDREF #IMPLIED
>
<!ELEMENT useShowWhen EMPTY>
<!ATTLIST useShowWhen
  show IDREF #REQUIRED
>

=== sillsdev/paws/src/org/sil/paws/resources/configuration/XMLWriterPracticalDescriptions/WriterPracticalExcl.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE portion SYSTEM "..\Data\PAWSSKWriterDescription.dtd">
<portion>
  <section1 id="sExcl">
	 <secTitle>Greetings, Interjections and Exclamations</secTitle>
	<p>
	<content>This section considers various types of common utterances which are not complete sentences.  Greetings, interjections and exclamations are covered in turn.</content>
	</p>
<section2 id="sExclGreet">
	<secTitle>Greetings</secTitle>
   <p contentType="ctComparativeIntro"><content>Greetings typically consist of a particular word or phrase, either standing alone or followed by a name or nominal phrase describing the person or animal being greeted.  Some are full sentences or full questions, such as </content> <langData>How do you do?</langData><content> and </content><langData>How are you?</langData> <content> and </content><langData>Have a good day!</langData> <content> which do not need to be treated separately. </content></p>
   <p contentType="ctComparativeIntro"><content>Some examples of English greetings are:
   </content><langData>Hi!</langData><content> and </content><langData>Howdy!</langData><content> and </content><langData>Goodby</langData><content> and </content><langData>Good day, sir</langData><content> and </content><langData>Good night, sweet baby</langData>
      <content>.</content>
   </p>
   <p contentType="ctPracticalIntro"><content>Greetings typically consist of a particular word or phrase, either standing alone or followed by a name or nominal phrase describing the person or animal being greeted.</content></p>
 <p><content>Examples of greetings in </content><langName/> <content> include:</content></p>
			<example>
				<interlinear exampleLoc="excl/greetExample"/>
			</example>
</section2>
<section2 id="sExclIntj">
	<secTitle>Interjections</secTitle>
<p contentType="ctComparativeIntro"><content>Interjections typically consist of a particular word or phrase that is used alone, usually with an exclamation point following it.  Though many of the words in interjections are not used in any other situation, regular adjectives are also used in this way.  Some examples of interjections in English are:
</content><langData>Ouch!</langData><content> and </content><langData>Gross!</langData><content> and </content><langData>Cool!</langData><content> and </content><langData>Jimminy Cricket!</langData>
</p>
   <p contentType="ctPracticalIntro"><content>Interjections typically consist of a particular word or phrase that is used alone, usually with an exclamation point following it.  Though many of the words in interjections are not used in any other situation, regular adjectives are also used in this way.</content></p>
      
<p><content>Examples of interjections in </content><langName/> <content> include:</content></p>
			<example>
				<interlinear exampleLoc="excl/intjExample"/>
			</example>
   <p><content/><langData>‘Yes’</langData><content> and </content><langData>‘No’</langData><content> answers to questions are similar to interjections.  </content><langName/><content> uses the following words to express these answers:</content></p>
<example>
<table border="1">
					<headerRow>
						<headerCol>Morphemes</headerCol>
						<headerCol>Gloss</headerCol>
					   <headerCol>Significance</headerCol>
					</headerRow>
					<row>
						<col exampleLoc="excl/yesExample"/>
					   <col ><gloss><content>ENTER GLOSS</content></gloss></col>
					   <col rowspan="1">
						   <gloss><content>yes</content></gloss>
						</col>
					</row>
					<row>
						<col exampleLoc="excl/noExample"/>
					   <col ><gloss><content>ENTER GLOSS</content></gloss></col>
					   <col rowspan="1">
						   <gloss><content>no</content></gloss>
						</col>
					</row>
</table>
</example>
</section2>
<section2 id="sExclExcl">
	<secTitle>Exclamations</secTitle>
<p contentType="ctComparativeIntro"><content>Exclamations typically consist of a particular word, such as </content><langData>how</langData><content> in English, followed by an adjective phrase and usually punctuated with an exclamation point.  English examples include: </content>
   <langData>How awful for you!</langData><content> and </content><langData>How nice!</langData><content> and </content><langData>How wonderful that your family could come!</langData>
</p>
   <p contentType="ctPracticalIntro"><content>Exclamations typically consist of a particular word followed by an adjective phrase and usually punctuated with an exclamation point.</content></p>  
<p show="swExclMNo"><langName/><content> does not have a special word which marks exclamations of this type, so they are no different than the interjections consisting of adjectives in the previous section.</content></p>
   <p show="swExclMYes"><langName/> <content> has one or more special words which signal an exclamation which occur </content>
      <text show="swExclMBefore"><content>before</content></text>
      <text show="swExclMAfter"><content>after</content></text>
      <text show="swExclMBoth"><content>on both sides of</content></text>
      <text show="swExclMEither"><content>on either side of</content></text>
      <text show="swExclMBeforeOrBoth"><content>before or on both sides of</content></text>
      <text show="swExclMAfterOrBoth"><content>after or on both sides of</content></text>
      <text show="swExclMEitherOrBoth"><content>on either side or on both sides of</content></text>
      <text show="swExclMNotOther"><content> the adjective phrase.  </content></text>
      <text show="swExclMOtherOnly"><content>___</content><contentCheckBoxOther contentLoc="excl/exclMOther"/><content>.    </content></text>
      <text show="swExclMPosAndOther"><content> the adjective phrase and it may also occur ___</content><contentCheckBoxOther contentLoc="excl/exclMOther"/><content>.  </content></text>
      
   <content>These exclamation marker words are:</content></p>
<example show="swExclMYes"><table border="1">
<headerRow>
	<headerCol>Exclamation Markers</headerCol>
	<headerCol>Gloss</headerCol>
</headerRow>
	<row>
		<col exampleLoc="excl/exclMExample"></col>
		<col ><gloss><content>ENTER GLOSS</content></gloss></col>
	</row>
</table>
</example>

   <p><content>Examples of exclamations in </content><langName/><content> include:</content></p>
   <example>
	  <interlinear exampleLoc="excl/exclExample"/>
   </example>
</section2>
  </section1>
<showWhen id="swExclMYes">
	<whenValue element="excl" attr="exclM" value="yes"></whenValue>
</showWhen>
<showWhen id="swExclMNo">
	<whenValue element="excl" attr="exclM" value="no"></whenValue>
</showWhen>
   <showWhen id="swExclMBefore">
      <whenValue element="excl/exclMBefore" attr="checked" value="yes"/>
      <and/>
      <whenValue element="excl/exclMAfter" attr="checked" value="no"/>
      <and/>
      <whenValue element="excl/exclMBoth" attr="checked" value="no"/>
   </showWhen>
   <showWhen id="swExclMAfter">
      <whenValue element="excl/exclMBefore" attr="checked" value="no"/>
      <and/>
      <whenValue element="excl/exclMAfter" attr="checked" value="yes"/>
      <and/>
      <whenValue element="excl/exclMBoth" attr="checked" value="no"/>
   </showWhen>
   <showWhen id="swExclMBoth">
      <whenValue element="excl/exclMBefore" attr="checked" value="no"/>
      <and/>
      <whenValue element="excl/exclMAfter" attr="checked" value="no"/>
      <and/>
      <whenValue element="excl/exclMBoth" attr="checked" value="yes"/>
   </showWhen>
   <showWhen id="swExclMEither">
      <whenValue element="excl/exclMBefore" attr="checked" value="yes"/>
      <and/>
      <whenValue element="excl/exclMAfter" attr="checked" value="yes"/>
      <and/>
      <whenValue element="excl/exclMBoth" attr="checked" value="no"/>
   </showWhen>
   <showWhen id="swExclMBeforeOrBoth">
      <whenValue element="excl/exclMBefore" attr="checked" value="yes"/>
      <and/>
      <whenValue element="excl/exclMAfter" attr="checked" value="no"/>
      <and/>
      <whenValue element="excl/exclMBoth" attr="checked" value="yes"/>
   </showWhen>
   <showWhen id="swExclMAfterOrBoth">
      <whenValue element="excl/exclMBefore" attr="checked" value="no"/>
      <and/>
      <whenValue element="excl/exclMAfter" attr="checked" value="yes"/>
      <and/>
      <whenValue element="excl/exclMBoth" attr="checked" value="yes"/>
   </showWhen>
   <showWhen id="swExclMEitherOrBoth">
      <whenValue element="excl/exclMBefore" attr="checked" value="yes"/>
      <and/>
      <whenValue element="excl/exclMAfter" attr="checked" value="yes"/>
      <and/>
      <whenValue element="excl/exclMBoth" attr="checked" value="yes"/>
   </showWhen>
   <showWhen id="swExclMNotOther">
      <whenValue element="excl/exclMOther" attr="checked" value="no"/>
   </showWhen>
   <showWhen id="swExclMOtherOnly">
      <whenValue element="excl/exclMBefore" attr="checked" value="no"/>
      <and/>
      <whenValue element="excl/exclMAfter" attr="checked" value="no"/>
      <and/>
      <whenValue element="excl/exclMBoth" attr="checked" value="no"/>
      <and/>
      <whenValue element="qp/NPDegreePosOther" attr="checked" value="yes"/>
   </showWhen>
   <showWhen id="swExclMPosAndOther">
      <whenValue element="excl/exclMBefore" attr="checked" value="yes"/>
      <and/>
      <whenValue element="excl/exclMOther" attr="checked" value="yes"/>
      <or/>
      <whenValue element="excl/exclMAfter" attr="checked" value="yes"/>
      <and/>
      <whenValue element="excl/exclMOther" attr="checked" value="yes"/>
      <or/>
      <whenValue element="excl/exclMBoth" attr="checked" value="yes"/>
      <and/>
      <whenValue element="excl/exclMOther" attr="checked" value="yes"/>
   </showWhen>
</portion>

=== sillsdev/paws/src/org/sil/paws/resources/configuration/XMLWriterPracticalDescriptions/WriterPracticalProp.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE portion SYSTEM "..\Data\PAWSSKWriterDescription.dtd">
<portion>
    <section1 id="sProp">
        <secTitle>Proper Names</secTitle>
       <p contentType="ctPracticalIntro">
          <content>Proper names are a special kind of noun or phrase that acts syntactically just like other nouns or nominal phrases.</content>
       </p>
       <p contentType="ctComparativeIntro">
            <content>Proper names are a special kind of noun or phrase that acts syntactically just like other nouns or nominal phrases.  In English, some proper names can stand alone, like </content>
            <langData>Sue</langData>
            <content> and </content>
            <langData>Russia</langData>
            <content>.  Others are like compound nouns, such as </content>
            <langData>George Washington</langData>
            <content>.  Proper names may also contain articles and/or </content>
            <case element="pp" attr="pPos">
                <caseText value="before">prepositional</caseText>
                <caseText value="after">postpositional</caseText>
                <caseText value="both">prepositional or postpositional</caseText>
                <caseText value="unknown">adpositional</caseText>
            </case>
            <content> phrases, as in </content>
            <langData>the United States of America</langData>
            <content>.  Many languages require an article before a name.  Appositives also occur, possibly including a possessor, as in </content>
            <langData>my son, David</langData>
		   <content>, but these will be handled later in section </content><sectionRef sec="sCoordAppositive"/><content>.  In addition, proper names can be modified by adjectives and relative clauses, as in </content>
            <langData>the good, old USA</langData>
            <content> or </content>
            <langData>the Susan Welch that I know</langData>
            <content>.</content>
        </p>
       <p show="swClassifiersYesPropYes"><content>In </content><langName/><content>, proper names carry classifiers just like nouns as part of the concord agreement system.</content></p>
       <p show="swClassifiersYesPropNo"><content>In </content><langName/><content>, proper names do not carry classifiers as nouns do as part of the concord agreement system.</content></p>
       <p show="swNPArtAndDemNotNo"><content>Proper names in </content><langName/><case element="prop" attr="pnDeterminer">
          <caseText value="none"> may not</caseText>
           <caseText value="no"> may but are not required to</caseText>
           <caseText value="yes"> must</caseText>
       </case><content> contain </content><case element="np" attr="artAndDem">
          <caseText value="article">an article</caseText>
          <caseText value="demonstrative">a demonstrative</caseText>
          <caseText value="both">an article and/or demonstrative</caseText></case><content> or a possessor.</content></p>
       <p>
            <content>Examples with simple and compound proper names in </content>
            <langName/>
            <content> include:</content>
        </p>
        <example>
            <interlinear exampleLoc="prop/example"/>
        </example>
            <p><content>Examples of proper names with </content>
            <case element="pp" attr="pPos">
                <caseText value="before">prepositional</caseText>
                <caseText value="after">postpositional</caseText>
                <caseText value="both">prepositional or postpositional</caseText>
                <caseText value="unknown">adpositional</caseText>
            </case>
            <content> phrases in </content>
            <langName/>
            <content> include:</content>
        </p>
        <example>
            <interlinear exampleLoc="prop/ppExample"/>
        </example>
        <p>
            <content>Some examples of proper names modified by relative clauses included in simple full sentences are:</content>
        </p>
        <example>
            <interlinear exampleLoc="prop/relClExample"/>
        </example>
    </section1>
   <showWhen id="swClassifiersYesPropYes">
	  <whenValue element="typology"  attr="classifier" value="yesAgr"/>
	  <and/>
	  <whenValue element="prop" attr="pnClassifier" value="yes"/>
   </showWhen>
   <showWhen id="swClassifiersYesPropNo">
	  <whenValue element="typology"  attr="classifier" value="yesAgr"/>
	  <and/>
	  <whenValue element="prop" attr="pnClassifier" value="no"/>
   </showWhen>
   <showWhen id="swNPArtAndDemNotNo">
	  <whenValue element="np" attr="artAndDem" value="no" negateValue="yes"/>
   </showWhen>
</portion>

=== sillsdev/paws/resources/configuration/XMLWriterPracticalDescriptions/WriterPracticalAdvCl.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE portion SYSTEM "..\Data\PAWSSKWriterDescription.dtd">
<portion>
    <section1 id="sAdvCl">
        <secTitle>Adverbial Clauses</secTitle>
        <p>
            <content>This section considers the complements that can follow temporal and reason adverbs, which were introduced in sections </content>
            <sectionRef sec="sAdvPTemporal"/>
            <content> and </content>
            <sectionRef sec="sAdvPReason"/>
            <content>.  All of these adverbial clauses act the same as simple adverbs, so they will be considered adverbial phrases with the appropriate type of complement.  Adverbial clauses may normally occur either sentence-initially or sentence-finally.</content>
        </p>
        <section2 id="sAdvClTemporal">
            <secTitle>Complements of Temporal Adverbs</secTitle>
            <p contentType="ctComparativeIntro">
			   <content>English examples of temporal adverbs with complements used in full sentences include: </content><langData>[Since then], John has been moody</langData><content>; </content>
			   <langData>John has been home [since last week]</langData><content>; </content><langData>[Since John has been home from the hospital] he is doing better</langData><content>; </content>
			   <langData>John is feeling fine [now that he is home from the hospital</langData><content>; </content><langData>The dog followed Sue everywhere [when she returned from college]</langData>
			   <content> and </content><langData>[When she returned from college], the dog followed Sue everywhere</langData><content>. These examples show that particular temporal adverbs allow certain types of complements.  For example, </content>
                <langData>since</langData>
				<content> can be followed by another temporal adverb or by a temporal nominal phrase or it may have a sentential complement.  The temporal adverb </content>
                <langData>when</langData>
                <content> also takes a finite sentential complement, whereas </content>
                <langData>now</langData>
				<content> has a finite clausal complement with a complementizer.</content>
            </p>
            <p>
                <content>In </content>
                <langName/>
               <content>, the temporal adverbs allow complements similar to those discussed in section </content>
               <sectionRef sec="sComp"/>
               <content>.  The complements occur </content>
                <case element="advcl" attr="advOrNPPos">
                    <caseText value="before">before</caseText>
                    <caseText value="after">after</caseText>
                    <caseText value="either">on either side of</caseText>
                    <caseText value="unknown">_______</caseText>
                </case>
                <content> the temporal adverb.  Examples of temporal adverbial clauses included in full sentences are:</content>
            </p>
            <example>
                <interlinear exampleLoc="advcl/tempSentExample"/>
            </example>
        </section2>
        <section2 id="sAdvClReason">
            <secTitle>Complements of Reason Adverbs</secTitle>
            <p contentType="ctComparativeIntro">
				<content>Adverbial phrases or clauses which express reason or purpose consist of adverbs which stand alone, such as </content>
                <langData>therefore</langData>
                <content> and </content>
                <langData>so</langData>
				<content> (which are sometimes considered sentential conjunctions), along with those that take various types of complement clauses.  English examples of reason or purpose adverbs which take clausal complements include: </content>
			   <langData>John rushed to the hospital [because Sue was in an accident</langData><content>; </content><langData>[Since Jill said that she likes him], Joe smiles all the time</langData>
			   <content>; </content><langData>Bill rushed to the airport [so that he could see Kay before she left]</langData><content>; </content><langData>The troops threw grenades at the enemy [in order to escape]</langData>
			   <content> and </content><langData>The troops threw grenades at the enemy [in order for the prisoners to escape]</langData>
                <content>.  In the examples, </content>
                <langData>because</langData>
                <content> and </content>
                <langData>since</langData>
                <content> take only finite sentential complements and </content>
                <langData>so</langData>
                <content> takes a finite clausal complement with a complementizer.  In contrast, </content>
                <langData>in order</langData>
				<content> takes either a nonfinite sentential complement with a pro-dropped subject or a nonfinite clausal complement with a complementizer.  This is the same set of complements as shown for </content>
                <langData>like</langData>
                <content> and </content>
                <langData>hate</langData>
                <content> in section </content>
                <sectionRef sec="sComp"/>
                <content>.</content>
            </p>
           <p contentType="ctPracticalIntro">
              <content>Adverbial phrases or clauses which express reason or purpose consist of adverbs which stand alone, such as </content>
              <langData>therefore</langData>
              <content> and </content>
              <langData>so</langData>
              <content> (which are sometimes considered sentential conjunctions), along with those that take various types of complement clauses similar to those discussed for verbs in section </content>
              <sectionRef sec="sComp"/>
              <content>.</content>
           </p>
           <p>
                <content>Examples of reason or purpose adverbial clauses in </content>
                <langName/>
                <content>, included in full sentences are:</content>
            </p>
            <example>
                <interlinear exampleLoc="advp/reasonExample"/>
            </example>
        </section2>
    </section1>
</portion>
