=== sillsdev/paws/src/org/sil/paws/resources/configuration/Data/PAWSSKHtmlMapper.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--DTD generated by XML Spy v3.5 (http://www.xmlspy.com)-->
<!-- DTD for PAWS Starter Kit XML to HTML and code mappers -->
<!ENTITY nbsp "&#160;">
<!ENTITY % embedded "#PCDATA | a | br | category | catMap | contents | example | feature |
						 featureChart | file | help | i | ol | p | section | span |
			 technicalTermRef | template | templateName | tool | tree | u | ul">
<!ENTITY % TechnicalTerms SYSTEM  "PAWSTechnicalTerms.dtd">
%TechnicalTerms; 

<!ELEMENT a (%embedded;)*>
<!ATTLIST a
	href CDATA #REQUIRED
	target CDATA #IMPLIED
>
<!ELEMENT and EMPTY>
<!ELEMENT br EMPTY>
<!ELEMENT button EMPTY>
<!ATTLIST button
	id ID #REQUIRED
	value (Back | Next | Yes | No) #REQUIRED
	goto CDATA #IMPLIED
	gotoNoGrammar CDATA #IMPLIED
	>
<!ELEMENT buttons (button, codeInfo?, ruleInfo?, button, codeInfo?, ruleInfo?)>
<!ELEMENT category (#PCDATA)>
<!-- content is the name of the syntactic category -->
<!ELEMENT catMap (#PCDATA)>
<!ATTLIST catMap
	id ID #REQUIRED
	dataItem CDATA #REQUIRED
>
<!ELEMENT checkbox (#PCDATA | textBox)* >
<!ATTLIST checkbox
	id ID #REQUIRED
	dataItem CDATA #REQUIRED
	checked (yes) #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT checkboxGroup (prompt, checkbox+)>
<!ATTLIST checkboxGroup
	id ID #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT closeParen EMPTY>
<!ELEMENT codeInfo (#PCDATA)>
<!ELEMENT contentCheckBoxOther EMPTY>
<!ATTLIST contentCheckBoxOther
   contentLoc CDATA #REQUIRED
   id ID #IMPLIED
><!ELEMENT contents (#PCDATA)>
<!ELEMENT div (textBox | prompt | radioGroup | instruction | codeInfo | ruleInfo | introduction | EnglishExample | br | div | table)*>
<!ATTLIST div
	id ID #REQUIRED
	show IDREF #REQUIRED
>
<!ELEMENT EnglishExample (exItem+)>
<!ELEMENT example (#PCDATA)>
<!ELEMENT exItem (#PCDATA | span | u | sub)*>
<!ATTLIST exItem
	label CDATA #IMPLIED
>
<!ELEMENT feature (#PCDATA)>
<!ELEMENT featureChart (featureRow)+>
<!ATTLIST featureChart
	types (yes | no) "yes"
	explanations (yes | no) "yes"
>
<!ELEMENT featureExplanation (#PCDATA | technicalTermRef)*>
<!ELEMENT featureItem (#PCDATA | technicalTermRef)*>
<!ATTLIST featureItem
	dataValue CDATA #REQUIRED
	name CDATA #REQUIRED
>
<!ELEMENT featureRow (featureType?, featureItem, featureExplanation, textBox?)+>
<!ATTLIST featureRow
	id ID #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT featureType (#PCDATA)>
<!ATTLIST featureType
	rowspan CDATA #IMPLIED
>
<!ELEMENT file (#PCDATA)>
<!ATTLIST file
	id ID #REQUIRED
	section CDATA #REQUIRED
>
<!--
transparent = 'yes' means do not show yellow background, let the grey background come through.
-->
<!ELEMENT form ((textBox | prompt | radioGroup | checkboxGroup | instruction | codeInfo | ruleInfo | introduction | EnglishExample | table | br | div)*, br?, buttons)>
<!ATTLIST form
	transparent (yes | no) "no"
	section CDATA #REQUIRED
>
<!ELEMENT help (#PCDATA)>
<!ATTLIST help
	href CDATA #REQUIRED
>
<!ELEMENT i (#PCDATA)>
<!ELEMENT groupName (#PCDATA)>
<!ATTLIST groupName
	dataItem CDATA #REQUIRED
	default CDATA #REQUIRED
	position (no | yesSpec | yesHead | yesHeadDiff) "no"
>
<!ELEMENT instruction (%embedded; | codeInfo | ruleInfo)*>
<!ATTLIST instruction
	id ID #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT introduction (%embedded; | codeInfo | ruleInfo)*>
<!ATTLIST introduction
	transparent (yes | no) "yes"
	id ID #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT li (%embedded;)*>
<!ATTLIST li
	id ID #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT not EMPTY>
<!ELEMENT ol (li+)>
<!ELEMENT p (%embedded;)*>
<!ATTLIST p
	style CDATA #IMPLIED
>
<!ELEMENT openParen EMPTY>
<!ELEMENT or EMPTY>
<!ELEMENT page (title, (introduction | EnglishExample | table | instruction)*, form, showWhen*, technicalTerms?)>
<!ATTLIST page
	id ID #REQUIRED
	count CDATA #IMPLIED
>
<!ELEMENT prompt (%embedded;)*>
<!ATTLIST prompt
	id ID #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT radio (%embedded;)*>
<!ATTLIST radio
	id ID #REQUIRED
	dataValue CDATA #REQUIRED
	checked (yes) #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT radioGroup (groupName, prompt, radio, (radio | codeInfo | ruleInfo | radioGroup | checkboxGroup)*)>
<!ATTLIST radioGroup
	id ID #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT ruleInfo (#PCDATA)>
<!ELEMENT span (%embedded;)*>
<!ATTLIST span
	id ID #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT section (#PCDATA)>
<!ATTLIST section
	number CDATA #REQUIRED
>
<!ELEMENT showWhen (openParen*, not?, (whenRadio | whenValue | whenCheckbox), ((or | and), openParen*, not?, (whenRadio | whenValue | whenCheckbox), closeParen*)*, closeParen*)>
<!ATTLIST showWhen
	id ID #REQUIRED
>
<!ELEMENT sub (#PCDATA)>
<!ELEMENT table (tr+) >
<!ATTLIST table
	id ID #IMPLIED
	show IDREF #IMPLIED
	class CDATA #IMPLIED
>
<!ELEMENT td (#PCDATA | contentCheckBoxOther)* >
<!ATTLIST td
	colspan CDATA #IMPLIED
>
<!ELEMENT textBox EMPTY>
<!ATTLIST textBox
	id ID #REQUIRED
	contenteditable (true | inherit | false) "inherit"
	dataItem CDATA #REQUIRED
	section CDATA #IMPLIED
	rows CDATA #IMPLIED
	cols CDATA #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT th (#PCDATA) >
<!ATTLIST th
	colspan CDATA #IMPLIED
>
<!ELEMENT title (#PCDATA | i)*>
<!ATTLIST title
	level CDATA #IMPLIED
>
<!ELEMENT template (#PCDATA)>
<!ELEMENT templateName (#PCDATA)>
<!ELEMENT tool (#PCDATA)>
<!ELEMENT tr (th | td)+ >
<!ATTLIST tr
	id ID #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT tree (#PCDATA | br)*>
<!ATTLIST tree
	img CDATA #IMPLIED
>
<!ELEMENT u (#PCDATA)>
<!ELEMENT ul (li+)>
<!ELEMENT whenCheckbox EMPTY>
<!ATTLIST whenCheckbox
	button IDREF #REQUIRED
>
<!ELEMENT whenRadio EMPTY>
<!ATTLIST whenRadio
	button IDREF #REQUIRED
>
<!ELEMENT whenValue EMPTY>
<!ATTLIST whenValue
	element CDATA #REQUIRED
	attr CDATA #REQUIRED
	value CDATA #REQUIRED
>

=== sillsdev/paws/resources/configuration/XmlPageDescriptions/IPIntran_fr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "..\Data\PAWSSKHtmlMapper.dtd" [
<!ENTITY TechnicalTerms SYSTEM  "TechnicalTerms_fr.xml">
]>
<?xml-stylesheet type="text/xsl" href="..\Transforms\PAWSSKHtmlMapper.xsl"?>
<page id="IPIntran" count="9.6.1">
    <title level="2">Phrases simples – Intransitives et Mouvement</title>
    <introduction>Les phrases simples <technicalTermRef term="ttIntransitive">intransitives</technicalTermRef> n’ont pas de <technicalTermRef term="ttComplements">compléments</technicalTermRef> après le verbe, tels que <example>La fille nage</example>. Les sujets de beaucoup de verbes intransitifs ont des sujets-<technicalTermRef term="ttExperiencer">expérient</technicalTermRef> et non des sujets-<technicalTermRef term="ttAgent">agent</technicalTermRef>, comme par exemple <example>Ma sœur a ri</example>.</introduction>
    <form section="ip">
        <prompt><br/>Les exemples de phrases intransitives dont les verbes ont un sujet-agent que vous avez saisis dans la <section number="1.">Questions générales de typologie – Le système casuel</section> sont repris ici. La première boite contient des exemples dont les sujets sont des syntagmes nominaux et la deuxième contient des sujets pronominaux.</prompt>
       <textBox id="IPExamplesIntranExample"  section="typology" dataItem="intExample" cols="80"/>
       <textBox id="IPExamplesIntranPnExample"  section="typology" dataItem="pnIntExample" cols="80"/>
        <prompt><br/>Les exemples de phrases intransitives dont les verbes ont un sujet-expérient que vous avez saisis dans la <section number="1.">Questions générales de typologie – Le système casuel</section> sont repris ici. La première boite contient des exemples dont les sujets sont des syntagmes nominaux et la deuxième contient des sujets pronominaux.</prompt>
       <textBox id="IPExperiencerIntExample"  section="typology" dataItem="experiencerIntExample" cols="80"/>
       <textBox id="IPExperiencerIntPnExample"  section="typology" dataItem="experiencerPnIntExample" cols="80"/>
       <br/>
       <instruction id="IPIntranExpInstruction" show="swExpNotNo">Since Experiencer subjects are distinct from Agent subjects in your language, add the feature <feature>experiencer</feature> to the verbs which have an Experiencer subject.</instruction>
       <br/>
        <introduction> Les verbes de mouvement contiennent un lieu sous la forme d’un syntagme prépositionel ou postpositionel, ou d’un adverbe. Des exemples français des verbes de mouvement comprennent :</introduction>
       <EnglishExample>
           <exItem label="1.">La jeune fille a traversé la rivière.</exItem>
           <exItem label="2.">Ma mère est allée au magasin.</exItem>
           <exItem label="3.">Mon professeur est venu ici.</exItem>
       </EnglishExample>
        <prompt><br/>Saisissez les exemples avec des verbes de mouvement ici :</prompt>
        <textBox id="IPExamplesMotionExample" dataItem="motionExample" cols="80"/>
        <instruction id="IPIntranInstruction">Partial subcategorization can be done as follows, without entering a feature on every verb: if a particular verb is intransitive and can never have anything but a subject, mark it with the feature <feature>intransitive</feature>.  (Do not consider temporal elements.)  If it is an intransitive motion verb that can have a locative PP or AdvP <span id="IPIntranFollow" show="swHeadInitial">following</span>
            <span id="IPIntranPrecede" show="swHeadFinal">preceding</span> it, add the feature <feature>motion</feature> to its lexical entry.  Since the motion verbs are a small, closed set, the feature must be entered in the lexicon on the appropriate verbs; the default setting is <feature>-motion</feature>.  Also, add the feature <feature>transitive_motion</feature> to any verbs like <example>put</example> which take an object and a locative.  
            Verbs like <example>move</example> can be either intransitive or transitive, so they should have both features <feature>motion transitive_motion</feature>.</instruction>
       <br/>
       <br/><buttons>
            <button id="IPIntranBack" value="Back" goto="IPContents_fr.htm"/>
            <button id="IPIntranNext" value="Next" goto="IPContents_fr.htm"/>
        </buttons>
    </form>
   <showWhen id="swExpNotNo">
     <not/> <whenValue element="typology" attr="caseExperiencer" value="no"/>
   </showWhen>
   <showWhen id="swHeadInitial">
        <whenValue element="typology" attr="wordOrder" value="SVO"/>
        <or/>
        <whenValue element="typology" attr="wordOrder" value="VOS"/>
        <or/>
        <whenValue element="typology" attr="wordOrder" value="VSO"/>
    </showWhen>
    <showWhen id="swHeadFinal">
        <whenValue element="typology" attr="wordOrder" value="SOV"/>
        <or/>
        <whenValue element="typology" attr="wordOrder" value="OVS"/>
        <or/>
        <whenValue element="typology" attr="wordOrder" value="OSV"/>
    </showWhen>
   &TechnicalTerms; 
</page>

=== sillsdev/paws/src/org/sil/paws/resources/configuration/XmlPageDescriptions/IPVoice_es.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "..\Data\PAWSSKHtmlMapper.dtd" [
<!ENTITY TechnicalTerms SYSTEM  "TechnicalTerms.xml">
]>
<?xml-stylesheet type="text/xsl" href="..\Transforms\PAWSSKHtmlMapper.xsl"?>
<page id="IPVoice" count="3/3">
   <title level="2">Las oraciones básicas - Otros indicadores de voz</title>
   <introduction>Algunas lenguas, como Tagalog y otras lenguas del Austronesio, poseen afijos en el verbo que ayuden a definir las relaciones de las frases nominales en la oración.  Este es algo semejante a <technicalTermRef term="ttVoice"/> pasiva para dar énfasis a alguna de sus frases nominales. 
      Los afijos verbales indican cuál frase nominal es la prominente y pueden implicar un cambio en el orden de las palabras y/o la marca de <technicalTermRef term="ttCase"/>. <br/><br/> Algunos ejemplos de Tagalog (Kroeger, Paul. 1993. Phrase structure and grammatical relations in Tagalog. Stanford, California: CSLI) que muestran un cambio en caso (pero no el orden de las palabras), en que el indicador de la voz refleja la relación grammatical del argumento nominativo son:
		</introduction>
	<table>
		<tr>
			<td>1.</td><td>Voz de actor:</td>	<td>B&lt;um&gt;ili</td><td>ang</td><td>lalake</td><td>ng</td><td>isda</td><td>sa</td><td>tindahan.</td>
		</tr>
		<tr>
			<td></td><td></td><td>PFV.AV-compre</td><td>NOM</td><td>hombre</td><td>GEN</td><td>pescado</td><td>DAT</td><td>tienda</td>
		</tr>
		<tr>
		   <td></td><td></td><td colspan="7">‘The man bought fish at the store.' (El hombre compra pescados en la tienda.)</td>
		</tr>
		<tr>
			<td>2.</td><td>Voz de objeto:</td><td>B&lt;in&gt;ili</td><td>ng</td><td>lalake</td><td>ang</td><td>isda</td><td>sa</td><td>tindahan.</td>
		</tr>
		<tr>
			<td></td><td></td><td>PFV.OV-compre</td><td>GEN</td><td>hombre</td><td>NOM</td><td>pescado</td><td>DAT</td><td>tienda</td>
		</tr>
		<tr>
		   <td></td><td></td><td colspan="7">‘A man bought the fish at the store.' (Los pescados son comprados por el hombre en la tienda.)</td>
		</tr>
		<tr>
			<td>3.</td><td>Voz de locativo:</td><td>B&lt;in&gt;il-han</td><td>ng</td><td>lalake</td><td>ng</td><td>isda</td><td>ang</td><td>tindahan.</td>
		</tr>
		<tr>
			<td></td><td></td><td>PFV.GV-compre</td><td>GEN</td><td>hombre</td><td>GEN</td><td>pescado</td><td>NOM</td><td>tienda</td>
		</tr>
		<tr>
		   <td></td><td></td><td colspan="7">‘The man bought fish at the store.' (En la tienda fue comprado el pescado por el hombre.)</td>
		</tr>
	</table>
	<form section="ip">
		<radioGroup>
			<groupName dataItem="voice" default="no">RIPvoice</groupName>
		   <prompt>¿Su lengua tiene indicadores de voz de este tipo especial? </prompt>
			<radio id="IPVoiceNo" dataValue="no">No</radio>
		   <radio id="IPVoiceYes" dataValue="yes">Sí</radio>
			</radioGroup>
	   <prompt id="IPVoiceNoPrompt" show="swIPVoiceNoAndFeaturesYes">ADVERTENCIA: En <section number="9.2">Las oraciones básicas - La flexión verbal</section> usted seleccionó algunos de los accidentes gramaticales de voz de este tipo especial para su lengua. Esto es inconsistente con su respuesta aquí. Por favor, o cambia su respuesta aquí para decir que su lengua tiene indicadores de voz de este tipo especial,
	      o vuelva a <section number="9.2">Las oraciones básicas - La flexión verbal</section> y desactive los accidentes gramaticales de voz de este tipo especial.</prompt>
	   <prompt id="IPVoiceYesPrompt" show="swIPVoiceYesAndFeaturesNo">ADVERTENCIA: En <section number="9.2">Las oraciones básicas - La flexión verbal</section> usted no seleccionó ningún accidente gramatical de voz de este tipo especial para su lengua. Esto es inconsistente con su respuesta aquí  Si su lengua tiene indicadores de voz de este tipo especial, 
	      vuelva a <section number="9.2">Las oraciones básicas - La flexión verbal</section> y seleccione los accidentes gramaticales de voz de este tipo especial y escriba las morfemas antes de regresando aquí.</prompt>
	   <prompt id="IPVoicePrompt" show="swIPVoiceYes">Escriba ejemplos de oraciones que muestran los indicadores de voz de este tipo especial aquí.  Sugeremos que usted escriba un sistema de oraciones similares que difieren solamente en los indicadores de voz, como en los ejemplos arriba.</prompt>
	   <textBox id="IPVoiceExample" dataItem="voiceExample" cols="50" show="swIPVoiceYes"/>
<br></br>	
		<radioGroup id="IPVoiceCase" show="swIPVoiceYes">
			<groupName dataItem="voiceCase" default="no">RIPVoiceCase</groupName>
		   <prompt>¿Su lengua expresa este tipo de voz a través de cambios en la marca del caso, como en Tagalog?</prompt>
		   <radio id="IPVoiceCaseNo" dataValue="no">No, los cambios de la voz se indicans con un cambio en el orden de las palabras en vez de marcar con el caso</radio>
		   <radio id="IPVoiceCaseYesNom" dataValue="yesNom" show="swCaseNomOrSplit">Sí, cuando un indicador de voz específico se marca en el verbo, la frase nominal correspondiente a esa voz se marca con el nominativo</radio>
		   <radio id="IPVoiceCaseYesAbs" dataValue="yesAbs" show="swCaseErgOrSplit">Sí, cuando un indicador de voz específico se marca en el verbo, la frase nominal correspondiente a esa voz se marca con el absolutivo</radio>
		</radioGroup>
	   <instruction id="IPVoiceInstruction" show="swIPVoiceYes">In the lexicon, mark voice affixes with the appropriate feature <feature>actorVoice</feature>,  
	      <feature>objectVoice</feature> (also for patient or conveyance or theme), <feature>dativeVoice</feature>, <feature>locativeVoice</feature>, <feature>instrumentalVoice</feature> or <feature>goalVoice</feature> if you have not already done so.  Note that the appropriate voice features should have been checked in <section number="9.2">Inflection Features</section>.
	   </instruction>
	   <instruction id="IPVoiceYesNomInstruction" show="swIPVoiceYesNom">The phrase structure rules for all the transitive and ditransitive constructions where the voice affix reflects the role of the nominative argument assume that the other main arguments have genitive case, and therefore, accusative case is not used. 
	      You may choose to have two sets of <span id="IPVoiceYesNomNYesSpan" show="swNPCaseNYes">case markers and </span>pronouns for accusative and genitive, so that the accusative can be used as objects of prepositions or postpositions, or, if they are not distinct, simply use the feature <feature>accusative.or.genitive</feature> on their lexical entries.  
	      However, if the same <span id="IPVoiceYesNomNYesSpan2" show="swNPCaseNYes">case markers and </span>pronouns are also used for indirect objects and possibly for Experiencer subjects, key instead the feature <feature>-nominative</feature> on their lexical entries to allow accusative, dative and genitive case.
	   </instruction>
	   <br/><br/>
		<buttons>
			<button id="IPVoiceBack" value="Back" goto="IPCausative.xml"/>
			<button id="IPVoiceNext" value="Next" goto="IPContents.htm"/>
		</buttons>
	</form>
   <showWhen id="swIPVoiceYes">
      <whenRadio button="IPVoiceYes"/>
   </showWhen>
   <showWhen id="swIPVoiceYesCase">
      <whenRadio button="IPVoiceYes"/>
      <and/><not/>
      <whenValue element="typology" attr="case" value="none"/> 
   </showWhen>
   <showWhen id="swNPCaseNYes">
      <whenValue element="np" attr="caseN" value="yes"/>
      <and/><not/>
      <whenValue element="typology" attr="case" value="none"/> 
   </showWhen>   <showWhen id="swIPVoiceYesNom">
      <whenRadio button="IPVoiceYes"/>
      <and/>
      <whenRadio button="IPVoiceCaseYesNom"/>
      <and/><not/>
      <whenValue element="typology" attr="case" value="none"/> 
   </showWhen>
   <showWhen id="swIPVoiceNoAndFeaturesYes">
      <whenRadio button="IPVoiceNo"/>
      <and/>
      <openParen/>
      <whenValue element="ip/ipInflFeatActorVoice" attr="checked" value="yes"/>
      <or/>
      <whenValue element="ip/ipInflFeatObjectVoice" attr="checked" value="yes"/>
      <or/>
      <whenValue element="ip/ipInflFeatDativeVoice" attr="checked" value="yes"/>
      <or/>
      <whenValue element="ip/ipInflFeatGoalVoice" attr="checked" value="yes"/>
      <or/>
      <whenValue element="ip/ipInflFeatLocativeVoice" attr="checked" value="yes"/>
      <closeParen/>
   </showWhen>
   <showWhen id="swIPVoiceYesAndFeaturesNo">
      <whenRadio button="IPVoiceYes"/>
      <and/>
      <whenValue element="ip/ipInflFeatActorVoice" attr="checked" value="no"/>
      <and/>
      <whenValue element="ip/ipInflFeatObjectVoice" attr="checked" value="no"/>
      <and/>
      <whenValue element="ip/ipInflFeatDativeVoice" attr="checked" value="no"/>
      <and/>
      <whenValue element="ip/ipInflFeatGoalVoice" attr="checked" value="no"/>
      <and/>
      <whenValue element="ip/ipInflFeatLocativeVoice" attr="checked" value="no"/>
   </showWhen>
   <showWhen id="swCaseErgOrSplit">
      <whenValue element="typology" attr="case" value="ergative"/>
      <or/>
      <whenValue element="typology" attr="case" value="split"/>
   </showWhen>
   <showWhen id="swCaseNomOrSplit">
      <whenValue element="typology" attr="case" value="nominative"/>
      <or/>
      <whenValue element="typology" attr="case" value="split"/>
   </showWhen>
   &TechnicalTerms; 
</page>

=== sillsdev/paws/src/org/sil/paws/resources/configuration/XmlPageDescriptions/IPCop_fr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "..\Data\PAWSSKHtmlMapper.dtd" [
<!ENTITY TechnicalTerms SYSTEM  "TechnicalTerms.xml">
]>
<?xml-stylesheet type="text/xsl" href="..\Transforms\PAWSSKHtmlMapper.xsl"?>
<page id="IPCop" count="1/3">
    <title level="2">Phrases Simples – Copulatifs</title>
    <introduction>Nous distinguons ici entre les verbes <technicalTermRef term="ttCopular">copulatifs</technicalTermRef> et les verbes de <technicalTermRef term="ttPerception">perception</technicalTermRef>.<br/><br/>
        Les phrases copulatives peuvent comprendre un syntagme adjectival, prépositionnel, postpositionnel, ou nominal comme complément du verbe copulatif. Certaines langues n’insistent pas qu’un verbe copulatif ou qu’un auxiliaire soit présent. Voici des exemples en français:</introduction>
        <EnglishExample>
            <exItem label="1.">La fille est belle.</exItem>
            <exItem label="2.">Suzanne est malade.</exItem>
            <exItem label="3.">Ma soeur est à l’hôpital.</exItem>
            <exItem label="4.">Il est le chef.</exItem>
        </EnglishExample>
    <form section="ip">
        <prompt>Entrez ici des exemples dans votre langue de phrases copulatifs:</prompt>
        <textBox id="IPExamplesCopularExample" dataItem="copularExample" cols="50"/>
        <radioGroup>
            <groupName dataItem="copular" default="yes">RIPCopVerb</groupName>
            <prompt>Est-ce que votre langue a un ou plusieurs verbes <technicalTermRef term="ttOvert">visibles</technicalTermRef> dans les phrases de type copulatif?</prompt>
            <radio id="IPCopVerbYes" dataValue="yes">Oui; et il faut un verbe copulatif</radio>
            <radio id="IPCopVerbYesOptional" dataValue="optional">Oui; la langue possède un verbe copulatif, mais dans plusieurs cas il est facultatif</radio>
            <radio id="IPCopVerbNo" dataValue="no">Non, il n’y a pas de verbe dans les phrases copulatifs</radio>
        </radioGroup>
       <prompt id="IPCopularVerb" show="swIPCopVerbYesOrOptional">
           <br/>Entrez les verbes copulatives dans le zone de texte, chacun sur une ligne individuelle : 
       </prompt>
       <textBox id="IPCopuparVerbExample" dataItem="copularVerb" show="swIPCopVerbYesOrOptional" rows="3"/>
       <radioGroup id="IPCopVerbNoTable" show="swIPCopVerbNoOrOptional">
                <groupName dataItem="copularAffix" default="no">RIPCopAffix</groupName>
           <prompt>Est-ce qu’il y a un affixe qui se trouve sur le prédicat nominal ou le prédicat adjectival dans les phrases copulatifs<span  id="IPCopVerbYesOptionalPrompt" show="swIPCopVerbYesOptional"> où un verbe copulatif est absent</span>?</prompt>
                <radio id="IPCopAffixNo" dataValue="no">Non</radio>
           <radio id="IPCopAffixYesPrefix" dataValue="yesPrefix">Oui, un préfixe</radio>
           <radio id="IPCopAffixYesSuffix" dataValue="yesSuffix">Oui, un suffixe</radio>
           <radio id="IPCopAffixYesEither" dataValue="yesEither">Oui, quelquefois on utilise un préfixe et quelquefois un suffixe</radio>
            </radioGroup>
       <prompt id="IPCopularAffix" show="swIPCopAffixNotNo">
           <br/>Entrez ici les affixes copulatifs qui apparaîssent sur le prédicat nominal ou le prédicat adjectival<span  id="IPCopVerbYesOptionalPrompt2" show="swIPCopVerbYesOptional"> quand un verbe copulatif est absent</span>, avec un tiret pour indiquer de quel côté il s’attache: 
       </prompt>
       <textBox id="IPCopuparAffixExample" dataItem="copularAffix" show="swIPCopAffixNotNo" rows="3"/>
       
        <instruction id="IPCopAffixYesEitherInstruction" show="swIPCopAffixYesEither">Add either of the features <feature>copular_prefix</feature> or <feature>copular_suffix</feature> to the appropriate affixes in the lexicon.</instruction>
        <instruction id="IPCopAffixYesPrefixInstruction" show="swIPCopAffixYesPrefix">Add the feature <feature>copular_prefix</feature> to the appropriate prefix(es) in the lexicon.</instruction>
        <instruction id="IPCopAffixYesSuffixInstruction" show="swIPCopAffixYesSuffix">Add the feature <feature>copular_suffix</feature> to the appropriate suffix(es) in the lexicon.</instruction>
        <instruction id="IPCopVerbYesInstruction" show="swIPCopVerbYesOrOptional">Add the feature <feature>copular</feature> to the verbs that take AdjP, PP or predicate nominative complements.  Since the copular verbs are a small, closed set, the feature must be entered in the lexicon on the appropriate verbs; the default setting is <feature>-copular</feature>.</instruction>   
        <br/><br/>              
        <introduction>Maintenant on considère les phrases avec des verbes de perception.<br/><br/>
            Les verbes de perception permettent d’habitude un syntagme adjectival comme complément, sauf dans les constructions superlatives où un syntagme nominal suit un verbe de perception, comme montré à la page suivante. Des exemples en français comprennent :</introduction>
       <EnglishExample>
           <exItem label="5.">La fille a l’aire joli.</exItem>
           <exItem label="6.">Elle semble sympathique.</exItem>
           <exItem label="7.">L’eau paraît trouble.</exItem>
       </EnglishExample> 
        <prompt>Entrez des exemples pareils en votre langue ici:</prompt>
       <textBox id="IPExamplesPerceptionExample" dataItem="perceptionExample" cols="50"/>
       <instruction id="IPCopPerceptionInstruction">Add the feature <feature>perception</feature> to the lexical entry of the perception verbs. Since the perception verbs are a small, closed set, the feature must be entered in the lexicon on the appropriate verbs; the default setting is <feature>-perception</feature>.</instruction>
       <br/>
        <introduction>Et les verbes copulatifs et les verbes de perception peuvent contenir un syntagme adjectival comme complément, là où une phrase ou bien une proposition complétive suit l’adjectif. On traitera ces constructions dans la <section number="10.">Propositions Complétives</section> au cours de la discussion  des verbes de perception qui agissent comme verbes « à montée ».</introduction>
       <br/><br/>
       <buttons>
            <button id="IPCopBack" value="Back" goto="IPContents.htm"/>
            <button id="IPCopNext" value="Next" goto="IPComparative.xml"/>
        </buttons>
    </form>
    <showWhen id="swHeadInitial">
        <whenValue element="typology" attr="wordOrder" value="SVO"/>
        <or/>
        <whenValue element="typology" attr="wordOrder" value="VOS"/>
        <or/>
        <whenValue element="typology" attr="wordOrder" value="VSO"/>
    </showWhen>
    <showWhen id="swHeadFinal">
        <whenValue element="typology" attr="wordOrder" value="SOV"/>
        <or/>
        <whenValue element="typology" attr="wordOrder" value="OVS"/>
        <or/>
        <whenValue element="typology" attr="wordOrder" value="OSV"/>
    </showWhen>
<showWhen id="swIPCopVerbYesOptional">
        <whenRadio button="IPCopVerbYesOptional"/>
</showWhen>
    <showWhen id="swIPCopVerbNoOrOptional">
        <whenRadio button="IPCopVerbNo"/>
        <or/>
        <whenRadio button="IPCopVerbYesOptional"/>
    </showWhen>
<showWhen id="swIPCopAffixYesEither">
<openParen/>
        <whenRadio button="IPCopVerbNo"/>
        <or/>
        <whenRadio button="IPCopVerbYesOptional"/>
<closeParen/> <and/>
    <whenRadio button="IPCopAffixYesEither"/>
</showWhen>
<showWhen id="swIPCopAffixYesPrefix">
<openParen/>
        <whenRadio button="IPCopVerbNo"/>
        <or/>
        <whenRadio button="IPCopVerbYesOptional"/>
<closeParen/> <and/>
    <whenRadio button="IPCopAffixYesPrefix"/>
</showWhen>
<showWhen id="swIPCopAffixYesSuffix">
<openParen/>
        <whenRadio button="IPCopVerbNo"/>
        <or/>
        <whenRadio button="IPCopVerbYesOptional"/>
<closeParen/> <and/>
    <whenRadio button="IPCopAffixYesSuffix"/>
</showWhen>
<showWhen id="swIPCopVerbYesOrOptional">
<whenRadio button="IPCopVerbYes"/>
        <or/>
        <whenRadio button="IPCopVerbYesOptional"/>
</showWhen>
   <showWhen id="swIPCopAffixNotNo">
      <whenRadio button="IPCopVerbNo"/>
      <and/><not/>
      <whenRadio button="IPCopAffixNo"/>
      <or/>
      <whenRadio button="IPCopVerbYesOptional"/>
      <and/><not/>
      <whenRadio button="IPCopAffixNo"/>
   </showWhen>
   &TechnicalTerms; 
</page>
