=== sillsdev/paws/src/org/sil/paws/resources/configuration/Data/PAWSSKHtmlMapper.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--DTD generated by XML Spy v3.5 (http://www.xmlspy.com)-->
<!-- DTD for PAWS Starter Kit XML to HTML and code mappers -->
<!ENTITY nbsp "&#160;">
<!ENTITY % embedded "#PCDATA | a | br | category | catMap | contents | example | feature |
						 featureChart | file | help | i | ol | p | section | span |
			 technicalTermRef | template | templateName | tool | tree | u | ul">
<!ENTITY % TechnicalTerms SYSTEM  "PAWSTechnicalTerms.dtd">
%TechnicalTerms; 

<!ELEMENT a (%embedded;)*>
<!ATTLIST a
	href CDATA #REQUIRED
	target CDATA #IMPLIED
>
<!ELEMENT and EMPTY>
<!ELEMENT br EMPTY>
<!ELEMENT button EMPTY>
<!ATTLIST button
	id ID #REQUIRED
	value (Back | Next | Yes | No) #REQUIRED
	goto CDATA #IMPLIED
	gotoNoGrammar CDATA #IMPLIED
	>
<!ELEMENT buttons (button, codeInfo?, ruleInfo?, button, codeInfo?, ruleInfo?)>
<!ELEMENT category (#PCDATA)>
<!-- content is the name of the syntactic category -->
<!ELEMENT catMap (#PCDATA)>
<!ATTLIST catMap
	id ID #REQUIRED
	dataItem CDATA #REQUIRED
>
<!ELEMENT checkbox (#PCDATA | textBox)* >
<!ATTLIST checkbox
	id ID #REQUIRED
	dataItem CDATA #REQUIRED
	checked (yes) #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT checkboxGroup (prompt, checkbox+)>
<!ATTLIST checkboxGroup
	id ID #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT closeParen EMPTY>
<!ELEMENT codeInfo (#PCDATA)>
<!ELEMENT contentCheckBoxOther EMPTY>
<!ATTLIST contentCheckBoxOther
   contentLoc CDATA #REQUIRED
   id ID #IMPLIED
><!ELEMENT contents (#PCDATA)>
<!ELEMENT div (textBox | prompt | radioGroup | instruction | codeInfo | ruleInfo | introduction | EnglishExample | br | div | table)*>
<!ATTLIST div
	id ID #REQUIRED
	show IDREF #REQUIRED
>
<!ELEMENT EnglishExample (exItem+)>
<!ELEMENT example (#PCDATA)>
<!ELEMENT exItem (#PCDATA | span | u | sub)*>
<!ATTLIST exItem
	label CDATA #IMPLIED
>
<!ELEMENT feature (#PCDATA)>
<!ELEMENT featureChart (featureRow)+>
<!ATTLIST featureChart
	types (yes | no) "yes"
	explanations (yes | no) "yes"
>
<!ELEMENT featureExplanation (#PCDATA | technicalTermRef)*>
<!ELEMENT featureItem (#PCDATA | technicalTermRef)*>
<!ATTLIST featureItem
	dataValue CDATA #REQUIRED
	name CDATA #REQUIRED
>
<!ELEMENT featureRow (featureType?, featureItem, featureExplanation, textBox?)+>
<!ATTLIST featureRow
	id ID #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT featureType (#PCDATA)>
<!ATTLIST featureType
	rowspan CDATA #IMPLIED
>
<!ELEMENT file (#PCDATA)>
<!ATTLIST file
	id ID #REQUIRED
	section CDATA #REQUIRED
>
<!--
transparent = 'yes' means do not show yellow background, let the grey background come through.
-->
<!ELEMENT form ((textBox | prompt | radioGroup | checkboxGroup | instruction | codeInfo | ruleInfo | introduction | EnglishExample | table | br | div)*, br?, buttons)>
<!ATTLIST form
	transparent (yes | no) "no"
	section CDATA #REQUIRED
>
<!ELEMENT help (#PCDATA)>
<!ATTLIST help
	href CDATA #REQUIRED
>
<!ELEMENT i (#PCDATA)>
<!ELEMENT groupName (#PCDATA)>
<!ATTLIST groupName
	dataItem CDATA #REQUIRED
	default CDATA #REQUIRED
	position (no | yesSpec | yesHead | yesHeadDiff) "no"
>
<!ELEMENT instruction (%embedded; | codeInfo | ruleInfo)*>
<!ATTLIST instruction
	id ID #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT introduction (%embedded; | codeInfo | ruleInfo)*>
<!ATTLIST introduction
	transparent (yes | no) "yes"
	id ID #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT li (%embedded;)*>
<!ATTLIST li
	id ID #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT not EMPTY>
<!ELEMENT ol (li+)>
<!ELEMENT p (%embedded;)*>
<!ATTLIST p
	style CDATA #IMPLIED
>
<!ELEMENT openParen EMPTY>
<!ELEMENT or EMPTY>
<!ELEMENT page (title, (introduction | EnglishExample | table | instruction)*, form, showWhen*, technicalTerms?)>
<!ATTLIST page
	id ID #REQUIRED
	count CDATA #IMPLIED
>
<!ELEMENT prompt (%embedded;)*>
<!ATTLIST prompt
	id ID #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT radio (%embedded;)*>
<!ATTLIST radio
	id ID #REQUIRED
	dataValue CDATA #REQUIRED
	checked (yes) #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT radioGroup (groupName, prompt, radio, (radio | codeInfo | ruleInfo | radioGroup | checkboxGroup)*)>
<!ATTLIST radioGroup
	id ID #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT ruleInfo (#PCDATA)>
<!ELEMENT span (%embedded;)*>
<!ATTLIST span
	id ID #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT section (#PCDATA)>
<!ATTLIST section
	number CDATA #REQUIRED
>
<!ELEMENT showWhen (openParen*, not?, (whenRadio | whenValue | whenCheckbox), ((or | and), openParen*, not?, (whenRadio | whenValue | whenCheckbox), closeParen*)*, closeParen*)>
<!ATTLIST showWhen
	id ID #REQUIRED
>
<!ELEMENT sub (#PCDATA)>
<!ELEMENT table (tr+) >
<!ATTLIST table
	id ID #IMPLIED
	show IDREF #IMPLIED
	class CDATA #IMPLIED
>
<!ELEMENT td (#PCDATA | contentCheckBoxOther)* >
<!ATTLIST td
	colspan CDATA #IMPLIED
>
<!ELEMENT textBox EMPTY>
<!ATTLIST textBox
	id ID #REQUIRED
	contenteditable (true | inherit | false) "inherit"
	dataItem CDATA #REQUIRED
	section CDATA #IMPLIED
	rows CDATA #IMPLIED
	cols CDATA #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT th (#PCDATA) >
<!ATTLIST th
	colspan CDATA #IMPLIED
>
<!ELEMENT title (#PCDATA | i)*>
<!ATTLIST title
	level CDATA #IMPLIED
>
<!ELEMENT template (#PCDATA)>
<!ELEMENT templateName (#PCDATA)>
<!ELEMENT tool (#PCDATA)>
<!ELEMENT tr (th | td)+ >
<!ATTLIST tr
	id ID #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT tree (#PCDATA | br)*>
<!ATTLIST tree
	img CDATA #IMPLIED
>
<!ELEMENT u (#PCDATA)>
<!ELEMENT ul (li+)>
<!ELEMENT whenCheckbox EMPTY>
<!ATTLIST whenCheckbox
	button IDREF #REQUIRED
>
<!ELEMENT whenRadio EMPTY>
<!ATTLIST whenRadio
	button IDREF #REQUIRED
>
<!ELEMENT whenValue EMPTY>
<!ATTLIST whenValue
	element CDATA #REQUIRED
	attr CDATA #REQUIRED
	value CDATA #REQUIRED
>

=== sillsdev/paws/resources/configuration/XmlPageDescriptions/CoordDP_en.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "..\Data\PAWSSKHtmlMapper.dtd">
<?xml-stylesheet type="text/xsl" href="..\Templates\PAWSSKHtmlMapper.xsl"?>
<page id="CoordDP" count="2/4">
	<title level="2">Coordination Constructions - Lists and Appositives</title>
	<introduction>Besides the basic coordination constructions where there is an overt conjunction between the conjuncts, nominal phrases especially can have other forms of coordination constructions.  We will deal with lists and appositives here.
	<br/><br/>
	Lists consist of three or more items that are conjoined to form a single nominal phrase.  The initial items are normally separated by commas and there is an overt conjunction before the final item in the list, though there are different possibilities, as in 3-4.  Some English examples of nominal phrases consisting of lists are:
	</introduction>
   <EnglishExample>
      <exItem label="1.">John, Bill, Sue and Mary</exItem>
      <exItem label="2.">John, Bill, Sue and/or Mary</exItem>
      <exItem label="3.">John and Bill or Sue and Mary</exItem>
      <exItem label="4.">a cat, two dogs, and a chicken but not a monkey</exItem>
   </EnglishExample>   
   <form section="coord" transparent="no">
      <prompt>Key how your language expresses lists within a nominal phrase here:</prompt>
      <textBox id="CoordListExample" dataItem="listExample"/>
<br/><br/>
      <introduction>Appositives normally consist of a name followed by a comma and then a description also followed by a comma, or the order may be reversed.  Some English examples include:
      </introduction>
	<EnglishExample>
	   <exItem label="5.">George Washington, the first President of the United States</exItem>
	   <exItem label="6.">my brother, James</exItem>
	</EnglishExample>
  <br/>
      <prompt>Key some nominal phrases containing appositives in your language here:</prompt>
      <textBox id="CoordAppositiveExample" dataItem="appositiveExample"/>
      <br/>
      <br/>
      <instruction id="CoordListCommaInstruction">Note that the comma is important in both of these constructions and may be useful in disambiguating list or appositive constructions from other types.  You can choose to make the comma (,) a word-formation character in <tool>CarlaStudio</tool>. Then make it a suffix or enclitic that can go on any word category and give it the feature <feature>comma</feature>.  The PC-Patr grammar constraints to disambiguate via commas are already provided, but you will need to activate them by removing the comment character in the DP rule <ruleInfo>option conjListAppos</ruleInfo>.  See a similar instruction for topics.</instruction><br/>
		<br/>
		<buttons>
			<button id="CoordDPBack" value="Back" goto="CoordMain.xml"/>
		   <button id="CoordDPNext" value="Next" goto="CoordCatMap.xml" gotoNoGrammar="Contents.htm"/>
		</buttons>
	</form>
   <showWhen id="swPPPosPrep">
      <whenValue element="pp" attr="pPos" value="before"/>
   </showWhen>
   <showWhen id="swPPPosPost">
      <whenValue element="pp" attr="pPos" value="after"/>
   </showWhen>
   <showWhen id="swPPPosBoth">
      <whenValue element="pp" attr="pPos" value="both"/>
      <or/>
      <whenValue element="pp" attr="pPos" value="unknown"/>
   </showWhen>
</page>

=== sillsdev/paws/resources/configuration/XmlPageDescriptions/CoordDP_fr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "..\Data\PAWSSKHtmlMapper.dtd">
<?xml-stylesheet type="text/xsl" href="..\Templates\PAWSSKHtmlMapper.xsl"?>
<page id="CoordDP" count="2/4">
   <title level="2">Constructions Coordonnées – Listes et Appositifs</title>
   <introduction>En plus des constructions coordonnées simples où il y a une conjonction évidente, les syntagmes nominaux surtout peuvent avoir d’autres formes de constructions coordonnées. Nous traiterons les listes et les appositifs ici.
	<br/><br/>
      Les listes sont formées de trois substantifs ou plusieurs qui sont conjoints pour former un seul syntagme nominal.  Les substantifs initiaux sont séparés normalement par des virgules et il y a une conjonction évidente devant le substantif final de la liste, mais il y a d’autres possibilités, telles que 3-4.  Certains exemples français de syntagmes nominaux en forme de liste sont:
	</introduction>
   <EnglishExample>
      <exItem label="1.">Jean, Guillaume, Susanne et Marie</exItem>
      <exItem label="2.">Jean, Guillaume, Susanne et/ou Marie</exItem>
      <exItem label="3.">Jean et Guillaume ou Susanne et Marie</exItem>
      <exItem label="4.">un chat, deux chiens et un poulet, mais pas un singe</exItem>
   </EnglishExample>   
   <form section="coord" transparent="no">
      <prompt>Entrez ici la manière dont votre langue exprime les listes dans un syntagme nominal:</prompt>
      <textBox id="CoordListExample" dataItem="listExample"/>
<br/><br/>
      <introduction>Les appositifs se forment normalement d’un nom suivi d’une virgule et puis une description suivie aussi d’une virgule, ou l’ordre peut être inverti.  Des exemples en français sont:
      </introduction>
	<EnglishExample>
	   <exItem label="5.">George Washington, le premier président des Etats Unis</exItem>
	   <exItem label="6.">mon frère, Jacques</exItem>
	</EnglishExample>
  <br/>
      <prompt>Entrez ici des syntagmes nominaux qui contiennent des appositifs de votre langue:</prompt>
      <textBox id="CoordAppositiveExample" dataItem="appositiveExample"/>
      <br/>
      <br/>
      <instruction id="CoordListCommaInstruction">Note that the comma is important in both of these constructions and may be useful in disambiguating list or appositive constructions from other types.  You can choose to make the comma (,) a word-formation character in <tool>CarlaStudio</tool>. Then make it a suffix or enclitic that can go on any word category and give it the feature <feature>comma</feature>.  The PC-Patr grammar constraints to disambiguate via commas are already provided, but you will need to activate them by removing the comment character in the DP rule <ruleInfo>option conjListAppos</ruleInfo>.  See a similar instruction for topics.</instruction><br/>
		<br/>
		<buttons>
			<button id="CoordDPBack" value="Back" goto="CoordMain.xml"/>
		   <button id="CoordDPNext" value="Next" goto="CoordCatMap.xml" gotoNoGrammar="Contents.htm"/>
		</buttons>
	</form>
   <showWhen id="swPPPosPrep">
      <whenValue element="pp" attr="pPos" value="before"/>
   </showWhen>
   <showWhen id="swPPPosPost">
      <whenValue element="pp" attr="pPos" value="after"/>
   </showWhen>
   <showWhen id="swPPPosBoth">
      <whenValue element="pp" attr="pPos" value="both"/>
      <or/>
      <whenValue element="pp" attr="pPos" value="unknown"/>
   </showWhen>
</page>

=== sillsdev/paws/resources/configuration/XmlPageDescriptions/PNMain_es.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "..\Data\PAWSSKHtmlMapper.dtd" [
<!ENTITY TechnicalTerms SYSTEM  "TechnicalTerms.xml">
]>
<?xml-stylesheet type="text/xsl" href="..\Transforms\PAWSSKHtmlMapper.xsl"?>
<page id="PNMain" count="1/3">
	<title>Los nombres propios</title>
   <introduction> Los nombres propios son una clase especial de sustantivos o frases nominalesque sintácticamente funcionan igual que otros sustantivos o frases nominales. En español, algunos nombres propios pueden presentarse solos, como  <example>Susana</example> y <example>Oaxaca</example>.  Otros funcionan como sustantivos compuestos, como <example>George Washington</example>.  Los nombres propios también pueden contener los artículos y/o <technicalTermRef term="ttAdpositionalPhrases"/>, como en <example>los Estados Unidos de América</example>.  Muchas lenguas requieren un artículo antes de un nombre. Appositives, posiblemente incluyendo un posesivo, como en <example>mi hijo, David</example>, también ocurren, pero apositivos se tratan más adelante en <section number="15."> Las construcciones coordinadas</section>.  Además, los nombres propios se pueden modificar por los adjetivos y cláusulas relativas, como en <example>México fuerte y orgulloso</example> o <example>la Susana que conozco</example>.</introduction>
	<form section="prop">
		<prompt>Escriba sus ejemplos nombres propios simples y compuestos, o los que se presentan con artículos, demonstratives, adjetivos o los posesivos, si se permite, aquí :</prompt>
		<textBox id="PNExample" dataItem="example"/>
	   <br/><br/>
	   <radioGroup id="PNClassifiersTable" show="swOTClassifierAgr">
	      <groupName dataItem="pnClassifier" default="no">RPNClassifiers</groupName>
	      <prompt>Usted dijo que su lengua tiene indicadores de clase para la concordancia en las frases nominales. ¿Utiliza los clasificadores para marcar los nombres propios también?</prompt>
	      <radio id="PNClassifiersNo" dataValue="no">No, los nombres propios no se marcan la clase</radio>
	      <radio id="PNClassifiersYes" dataValue="yes">Sí, los nombres propios se marcan la clase lo mismo que sustantivos</radio>
	   </radioGroup>
	   <radioGroup id="PNDeterminersTable" show="swNPArtAndDemNotNo">
	      <groupName dataItem="pnDeterminer" default="no">RPNDeterminer</groupName>
	      <prompt>¿Se requieren los nombres propios en su lengua contener <span id="PNArtOnlySpan" show="swNPArtAndDemArt">un artículo</span>
	         <span id="PNDemOnlySpan" show="swNPArtAndDemDem">un demostrativo</span><span id="PNArtAndDemSpan" show="swNPArtAndDemBoth">un artículo o un demostrativo</span> o un posesivo?</prompt>
	   	<radio id="PNDeterminerNone" dataValue="none">No, no se permite ningún determinante en los nombres propios</radio>
	   	<radio id="PNDeterminerNo" dataValue="no">No, pueden contener estos elementos pero no son requiridos</radio>
	   	<radio id="PNDeterminerYes" dataValue="yes">Sí, cada nombre propio debe contener al menos uno de estos elementos</radio>
	   </radioGroup>
	   <br/>
		<br/>
		<prompt>Escriba sus ejemplos de nombres propios con frases adposicionales aquí:</prompt>
		<textBox id="PNPPExample" dataItem="ppExample"/>
		<br/>
		<br/>
	   <prompt>Escriba sus ejemplos de oraciones completas (pero simples) con los nombres propios modificados con las cláusulas relativas aquí:</prompt>
		<textBox id="PNRelClExample" dataItem="relClExample"/>
		<br/>
		<br/>
		<buttons>
			<button id="PNMainBack" value="Back" goto="Contents.htm"/>
		    <button id="PNMainNext" value="Next" goto="PNCatMap.xml" gotoNoGrammar="Contents.htm"/>
		</buttons>
	</form>
   <showWhen id="swOTClassifierAgr">
      <whenValue element="typology" attr="classifier" value="yesAgr"/>   
   </showWhen>
   <showWhen id="swNPArtAndDemArt">
      <whenValue element="np" attr="artAndDem" value="article"/>
   </showWhen>
   <showWhen id="swNPArtAndDemDem">
      <whenValue element="np" attr="artAndDem" value="demonstrative"/>
   </showWhen>
   <showWhen id="swNPArtAndDemBoth">
      <whenValue element="np" attr="artAndDem" value="both"/>
   </showWhen>
   <showWhen id="swNPArtAndDemNotNo">
      <whenValue element="np" attr="artAndDem" value="article"/>
      <or/>
      <whenValue element="np" attr="artAndDem" value="demonstrative"/>
      <or/>
      <whenValue element="np" attr="artAndDem" value="both"/>
   </showWhen>
   &TechnicalTerms; 
   
</page>

=== sillsdev/paws/src/org/sil/paws/resources/configuration/XmlPageDescriptions/IPMain_fr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "..\Data\PAWSSKHtmlMapper.dtd">
<?xml-stylesheet type="text/xsl" href="..\Templates\PAWSSKHtmlMapper.xsl"?>
<page id="IPMain" count="9.1.1">
    <title level="2">Phrases simples</title>
   <instruction id="IPMainIntroNotPractical" show="swNotPractical">In this section, we want to handle copular, intransitive, transitive and ditransitive sentences in their basic word order (i.e. not changed by focus, topic, interrogative, or negation constructions).  Inflection and agreement features on verbs, cases when a subject may be missing, auxiliaries, and sentences with passive and other voice changes are also covered.
      <br/>
      <br/>
        The data is in surface form, so the grammar must model surface structure, not the underlying structure before any derivational movement.<br/>
        <br/>
The trees you see will be in an X-bar theory form, as much as is possible for modelling the surface structure without movement.  This means that sentences are Inflectional Phrases (IPs) rather than the traditional S.  The subject usually occupies the specifier position, the head is an inflectional or auxiliary element, and the complement is the VP predicate.  For example, the tree for a transitive sentence in an SVO language, like English will be:
<tree img="TreeDescriptions/PawsIPSVO.png"/>
        <help href="../Help/Cbgbtext.doc#XBarTheory">(Click here to see more on the the IP phrase structure of sentences and X-Bar Theory in general.)</help>
        <br/>
        <br/>
SOV, VOS, and OVS word orders can be handled by taking the mirror image of the appropriate subtrees above.  VSO and OSV word order must have the subject internal to the VP, however, so the flatter structure shown here for VSO word order will be used:
<tree img="TreeDescriptions/PawsIPVSO.png"/>
        <br/>
        <br/>
The basic issues to be dealt with are presented here for your consideration and gathering of appropriate data, then the questions relevant to the basic word order of your language (as determined in section <section number="1">Overall Typology Questions</section>) will deal with the details of setting up the phrase structure rules and lexical features and constraints.
</instruction>
    <introduction id="IPMainIntroPractical" show="swPractical">Dans cette section nous traiterons les phrases copulatives, intransitives, transitives ou ditransitives, dans lesquelles aucun terme n’est  marqué (c’est-à-dire modifié par unede focalisation, de topicalisation, interrogative ou négative). 
        <br/>
        <br/>
        Nous couvrirons aussi les caractéristiques de la flexion et de l’accord des verbes, les cas où le sujet est omis, les verbes auxiliaires, les impératifs, les subjonctifs, les conditionnels ainsi que les constructions passives et d’autres changements de voix.
    </introduction>
    <form section="ip" transparent="yes">
        <br/>
        <buttons>
            <button id="IPMainBack" value="Back" goto="IPContents_fr.htm"/>
            <button id="IPMainNext" value="Next" goto="IPContents_fr.htm"/>
        </buttons>
    </form>
    <showWhen id="swNotPractical">
        <whenValue  element="paws" attr="outputGrammar" value="True"/>
    </showWhen>
    <showWhen id="swPractical">
        <whenValue  element="paws" attr="outputGrammar" value="False"/>
    </showWhen>
</page>

=== sillsdev/paws/src/org/sil/paws/resources/configuration/XmlPageDescriptions/QTesting_en.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "../Data/PAWSSKHtmlMapper.dtd">
<?xml-stylesheet type="text/xsl" href="..\Templates\PAWSSKHtmlMapper.xsl"?>
<page id="QTesting" count="11.9">
	<title level="2">Questions - Testing</title>
	<form section="q">
		<instruction>To test what you have done so far, save your work now.  This will generate the test file and grammar rules file created to this point.
			<p>
			Process the text file <file id="QTestingFile" section="Q">xxxQTest.txt</file> per the instructions on the 
				<a onclick="pawsApp.launchWebPage('Q/HTMs/FLExSetup_en.htm')" href="">FLEx setup</a> page or the
				<a onclick="pawsApp.launchWebPage('Q/HTMs/CarlaStudioSetup_en.htm')" href="">CARLAStudio setup</a> page, depending on which you are using.</p>
			<p>If any words fail to be parsed by your morphological parser, then the syntactic parser cannot parse any phrases or sentences those words are included in, 
				so you need to fix the problem with the morphlogical parser first.</p>
			<p>You may also find you need to change your answers on the previous pages of PAWS about the order of elements in the phrase structure rules.
			Or you may need to use the Category Mapper on the previous page to correct differences between your categories and those used by PAWS.  
			Make the changes as needed.</p>
			<p>If you have changed anything on the pages within PAWS, you will need to return to this page and then save the files again.  
				Rerun the parsers and check the results again.</p> 
			<p>Please check off this section now in ‘Contents’ and then proceed to
				<section number="12">Relative Clauses</section> when you are ready.
			</p>
		</instruction>
		<br/>
		<buttons>
			<button id="QTestingBack" value="Back" goto="QCatMap.xml"/>
			<button id="QTestingNext" value="Next" goto="Contents_en.htm"/>
		</buttons>
	</form>
</page>

=== sillsdev/paws/resources/configuration/XmlPageDescriptions/QCont_fr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "..\Data\PAWSSKHtmlMapper.dtd">
<?xml-stylesheet type="text/xsl" href="..\Templates\PAWSSKHtmlMapper.xsl"?>
<page id="QCont" count="5/9">
    <title level="2">Questions – La structure du syntagme dans les questions de contenu</title>
    <introduction id="QContIntroNotPractical" show="swNotPractical">Depending on the basic word order of your language, content questions may be formed with or without fronting an interrogative phrase.  Head-final languages (SOV, OVS, and OSV) usually do not have movement of an interrogative phrase in content questions, while head-initial languages (SVO, VOS, and VSO) usually require fronting of an interrogative phrase.<br/>
        <br/>In languages like English, the interrogative word or phrase must be fronted.  In the trees, this fronting will be to the specifier of CP.  Sample trees for main clause and embedded content questions in English are shown here:
<tree img="TreeDescriptions/PawsMainContentQues.png"/>
        <br/>
        <tree img="TreeDescriptions/PawsEmbContentQues.png"/>
        <br/>
        <help href="Help/Cbgbtext.doc#ContentQuestions">Click here for more information about the CP phrase structure of content questions.</help>
        <br/>
        <br/>
In languages without fronting for interrogatives, the phrase structure of a content question will either be the same as a Yes/No question with a question marker or auxiliary in the head of CP position or just the same as a normal sentence (IP).  In either case, the interrogative phrase appears in its normal argument positon.  
<br/>
<br/>
Many SOV languages optionally allow movement of an interrogative phrase to the position immediately before the verb, which will be within the VP in the tree structures used here.
        </introduction>
    <introduction id="QContIntroPractical" show="swPractical">Selon l’ordre syntaxique fondamental des phrases, les questions de contenu peuvent se former avec ou sans syntagme interrogatif en tête. Les langues à tête finale (SOV, OVS, et OSV) n’ont pas de mouvement du syntagme interrogatif dans les questions de contenu; dans les langues à tête initiale (SVO, VOS, et VSO) le syntagme interrogatif est habituellement en position initiale. <br/>
        <br/>Pour les langues comme le français et l’anglais le syntagme interrogatif vient en tête.
        <br/>
        <br/>
        Pour les langues où l’interrogatif ne figure pas en tête, la structure syntaxique d’une question de contenu sera identique à la structure d’une question oui/non; le marqueur interrogatif ou l’auxiliaire interrogatif se place ou bien dans la position de complément, ou tout comme dans une phrase normale.  Dans les deux cas le syntagme interrogatif prend sa place d’argument habituelle  
        <br/>
        <br/>
        Beaucoup de langues SOV permettent le déplacement du syntagme interrogatif directement avant le verbe.
    </introduction>
    <form section="q" transparent="yes">
        <br/>
        <buttons>
            <button id="QContBack" value="Back" goto="QWh.xml"/>
            <button id="QContNext" value="Next" goto="QMainCont.xml"/>
        </buttons>
    </form>
    <showWhen id="swNotPractical">
        <whenValue  element="paws" attr="outputGrammar" value="True"/>
    </showWhen>
    <showWhen id="swPractical">
        <whenValue  element="paws" attr="outputGrammar" value="False"/>
    </showWhen>
</page>
