=== sillsdev/paws/src/org/sil/paws/resources/configuration/Data/PAWSSKWriterDescription.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--DTD generated by XML Spy v3.5 (http://www.xmlspy.com)-->
<!-- DTD for PAWS Starter Kit Writer Page Description  -->
<!-- Entity definitions -->
<!ENTITY % chunk "p | example | table | tablenumbered | ol | ul | dl">
<!ENTITY % embedded "case | text | langData | langName | gloss | exampleRef | sectionRef | appendixRef | comment | object | br | category | feature | img | translatorInstruction | citation | endnote | contentCheckBoxOther">
<!ENTITY nbsp "&#160;">
<!ELEMENT and EMPTY>
<!ELEMENT appendix (secTitle, (%chunk; | section1 | section2)*)>
<!ATTLIST appendix
	id ID #REQUIRED
	label CDATA #IMPLIED
>
<!ELEMENT appendixRef EMPTY>
<!ATTLIST appendixRef
	app IDREF #REQUIRED
>
<!ELEMENT br EMPTY>
<!ELEMENT caption (content | %embedded;)*>
<!-- content -->
<!ELEMENT case (caseText*)>
<!ATTLIST case
  element CDATA #REQUIRED
  attr CDATA #REQUIRED
>
<!ELEMENT caseText (#PCDATA|case)*>
<!ATTLIST caseText
  value CDATA #REQUIRED
>
<!ELEMENT category (#PCDATA)>
<!-- content is the name of the syntactic category -->
<!ELEMENT citation EMPTY>
<!ATTLIST citation
    ref IDREF #REQUIRED
    page CDATA #IMPLIED
    author (yes | no) "yes"
    paren (both | none | initial | final) #IMPLIED
>
<!ELEMENT col (content | langData | gloss | case)*>
<!-- the content of rowspan actually gets calculated ono the fly; so just use any number in the description page -->
<!ATTLIST col
	align (left | center | right | justify) "left"
  class CDATA #IMPLIED
  show IDREF #IMPLIED
  exampleLoc CDATA #IMPLIED
  colspan CDATA #IMPLIED
  rowspan CDATA #IMPLIED
 >
<!-- comments are for the author.  The intent is that they will not show up in
	 the formatted version of the paper. -->
<!ELEMENT comment (#PCDATA | %embedded;)*>
<!ELEMENT content (#PCDATA)>
<!ELEMENT contentCheckBoxOther EMPTY>
<!ATTLIST contentCheckBoxOther
   contentLoc CDATA #REQUIRED
>
<!-- definition description -->
<!ELEMENT dd (content | %embedded; | %chunk;)*>
<!-- content -->
<!ATTLIST dd
  show IDREF #IMPLIED
>
<!-- definition list -->
<!ELEMENT dl (dt | dd)*>
<!ATTLIST dl
  show IDREF #IMPLIED
>
<!-- definition term -->
<!ELEMENT dt (content | %embedded; | %chunk;)*>
<!-- content -->
<!ATTLIST dt
  show IDREF #IMPLIED
>
<!ELEMENT endnote (p)*>
<!ATTLIST endnote
    id ID #REQUIRED
>
<!ELEMENT example (interlinear | table)>
<!ATTLIST example
  num ID #IMPLIED
  show IDREF #IMPLIED
  contentType IDREF #IMPLIED
>
<!-- references to example numbers or example number/letter.
	 Use just num for the example number.
	 Use just letter for an example number/letter combination.
	 One may include parentheses around the date ("both", the default), or
	   one may have no parentheses or just initial or just final.
	 One may append some punctuation (punct) to the end of the number.
	 One may only include the letter (and not the number). -->
<!ELEMENT exampleRef EMPTY>
<!ATTLIST exampleRef
  num CDATA #IMPLIED
  letter CDATA #IMPLIED
  equal (no | yes) "no"
  punct CDATA #IMPLIED
  paren (none | both | initial | final) #IMPLIED
  letterOnly (no | yes) "no"
>
<!ELEMENT feature (#PCDATA)>
<!-- gloss is a way to tag some text as being a gloss in a particular language. -->
<!ELEMENT gloss (content | %embedded;)*>
<!-- content -->
<!ELEMENT headerCol (#PCDATA| langName|object)*>
<!ATTLIST headerCol
	align (left | center | right | justify) "left"
  class CDATA #IMPLIED
  show IDREF #IMPLIED
>
<!ELEMENT headerRow (headerCol+)>
<!ATTLIST headerRow
  class CDATA #IMPLIED
  show IDREF #IMPLIED
>
<!ELEMENT img EMPTY>
<!ATTLIST img
  src CDATA #REQUIRED
>
<!ELEMENT interlinear EMPTY>
<!ATTLIST interlinear
  exampleLoc CDATA #REQUIRED
>
<!-- langData is a way to tag some text as belonging to a particular language. -->
<!ELEMENT langData (#PCDATA)>
<!ATTLIST langData
	lang CDATA #IMPLIED
>
<!-- content -->
<!ELEMENT langName EMPTY>
<!-- object is a generic way to tag a special kind of object.  One can
	 use the CSS stylesheet to format these objects by referring to the
	 class attribute.  -->
<!-- list element -->
<!ELEMENT li (content | %embedded; | %chunk;)*>
<!-- content -->
<!ATTLIST li
  id ID #IMPLIED
  show IDREF #IMPLIED
>
<!ELEMENT object (content | %embedded;)*>
<!-- content -->
<!ATTLIST object
  class CDATA #REQUIRED
>
<!-- ordered list -->
<!ELEMENT ol (li | ol | ul)*>
<!ATTLIST ol
  show IDREF #IMPLIED
>
<!ELEMENT or EMPTY>
<!ELEMENT p (content | %embedded;)*>
<!-- content -->
<!ATTLIST p
  style CDATA #IMPLIED
  show IDREF #IMPLIED
  contentType IDREF #IMPLIED
>
<!ELEMENT portion ((appendix+ |section1+), showWhen*)>
<!ELEMENT row (headerCol?, col+)>
<!ATTLIST row
  class CDATA #IMPLIED
  show IDREF #IMPLIED
>
<!ELEMENT secTitle (#PCDATA | %embedded;)*>
<!ELEMENT section1 (secTitle, (%chunk; | section2)*)>
<!ATTLIST section1
  id ID #REQUIRED
  show IDREF #IMPLIED
>
<!ELEMENT section2 (secTitle, (%chunk; | section3)*)>
<!ATTLIST section2
  id ID #REQUIRED
  show IDREF #IMPLIED
>
<!ELEMENT section3 (secTitle, (%chunk; | section4)*)>
<!ATTLIST section3
  id ID #REQUIRED
  show IDREF #IMPLIED
>
<!ELEMENT section4 (secTitle, (%chunk; | section5)*)>
<!ATTLIST section4
  id ID #REQUIRED
  show IDREF #IMPLIED
>
<!ELEMENT section5 (secTitle, (%chunk; | section6)*)>
<!ATTLIST section5
  id ID #REQUIRED
  show IDREF #IMPLIED
>
<!ELEMENT section6 (secTitle, (%chunk;)*)>
<!ATTLIST section6
  id ID #REQUIRED
  show IDREF #IMPLIED
>
<!-- references to sections, etc. -->
<!ELEMENT sectionRef EMPTY>
<!ATTLIST sectionRef
  sec CDATA #REQUIRED
>
<!ELEMENT showWhen ((whenValue | useShowWhen), ((or | and), (whenValue | useShowWhen))*)>
<!ATTLIST showWhen
  id ID #REQUIRED
>
<!ELEMENT table (caption?, headerRow*, row+)>
<!ATTLIST table
  border CDATA #IMPLIED
  class CDATA #IMPLIED
  show IDREF #IMPLIED
>
<!ELEMENT tablenumbered (table)>
<!ATTLIST tablenumbered
  id ID #IMPLIED
  contentType IDREF #IMPLIED
  show IDREF #IMPLIED
>
<!ELEMENT text (content | %embedded;)*>
<!ATTLIST text
  show IDREF #REQUIRED
>
<!ELEMENT translatorInstruction (#PCDATA)>

<!ELEMENT whenValue EMPTY>
<!ATTLIST whenValue
  element CDATA #REQUIRED
  attr CDATA #IMPLIED
  value CDATA #REQUIRED
  negateValue (yes | no) "no"
>
<!-- unordered list -->
<!ELEMENT ul (li | ol | ul)*>
<!ATTLIST ul
  show IDREF #IMPLIED
  contentType IDREF #IMPLIED
>
<!ELEMENT useShowWhen EMPTY>
<!ATTLIST useShowWhen
  show IDREF #REQUIRED
>

=== sillsdev/paws/src/org/sil/paws/resources/configuration/XMLWriterPracticalFrenchDescriptions/WriterFrPracticalProp.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE portion SYSTEM "..\Data\PAWSSKWriterDescription.dtd">
<portion>
    <section1 id="sProp">
        <secTitle>Noms propres</secTitle>
       <p contentType="ctPracticalIntro">
           <content>Les noms propres sont un type particulier de substantif ou de syntagme qui fonctionne tout comme les autres substantifs ou syntagmes nominaux sur le plan syntaxique.</content>
       </p>
       <p contentType="ctComparativeIntro">
           <content>Les noms propres sont un type particulier de substantif ou de syntagme qui fonctionne tout comme les autres substantifs ou syntagmes nominaux sur le plan syntaxique.  En français, certains noms propres peuvent se présenter seuls, comme </content>
            <langData>Susanne</langData>
            <content> et </content>
            <langData>Russie</langData>
           <content>.  D’autres sont comme les substantifs composés, tels que </content>
            <langData>George Washington</langData>
           <content>.  Les noms propres peuvent aussi contenir des articles et/ou des syntagmes </content>
            <case element="pp" attr="pPos">
                <caseText value="before">prépositionnels</caseText>
                <caseText value="after">postpositionnels</caseText>
                <caseText value="both">prépositionnels ou postpositionnels</caseText>
                <caseText value="unknown">adpositionnels</caseText>
            </case>
           <content> comme </content>
           <langData>les Etats-Unis d’Amérique</langData>
           <content>.  Bien des langues exigent un article devant un nom.  Les appositifs se présentent, parfois avec un possesseur, comme </content>
           <langData>mon fils, David</langData>
           <content> mais ils seront traités plus tard dans la section </content><sectionRef sec="sCoordAppositive"/><content>.  En plus, les noms propres peuvent être modifiés par des adjectifs et des propositions relatives, comme dans  </content>
           <langData>la belle France</langData>
            <content> ou </content>
           <langData>la Susanne Leblanc que je connais</langData>
            <content>.</content>
        </p>
        <p show="swClassifiersYesPropYes"><content>En </content><langName/><content>, les noms propres portent des classificateurs qui marquent l’accord, comme pour les substantifs.</content></p>
        <p show="swClassifiersYesPropNo"><content>En </content><langName/><content>, les noms propres ne portent pas de classificateurs pour marquer l’accord comme pour les substantifs.</content></p>
        <p show="swNPArtAndDemNotNo"><content>Les nom propres en </content><langName/><case element="prop" attr="pnDeterminer">
            <caseText value="none"> ne peuvent pas</caseText>
            <caseText value="no"> peuvent, mais ce n’est pas obligatoire</caseText>
            <caseText value="yes"> doivent</caseText>
       </case><content> contenir </content><case element="np" attr="artAndDem">
          <caseText value="article">un article</caseText>
           <caseText value="demonstrative">un démonstratif</caseText>
           <caseText value="both">un article et/ou un démonstratif</caseText></case><content> ou un possesseur.</content></p>
       <p>
           <content>Voice quelques exemples avec des noms propres simples et composés en </content>
            <langName/>
           <content> :</content>
        </p>
        <example>
            <interlinear exampleLoc="prop/example"/>
        </example>
        <p><content>Voice quelques exemples de noms propres avec des syntagmes </content>
            <case element="pp" attr="pPos">
                <caseText value="before">prépositionnels</caseText>
                <caseText value="after">postpositionnels</caseText>
                <caseText value="both">prépositionnels ou postpositionnels</caseText>
                <caseText value="unknown">adpositionnels</caseText>
            </case>
            <content> en </content>
            <langName/>
                <content> :</content>
        </p>
        <example>
            <interlinear exampleLoc="prop/ppExample"/>
        </example>
        <p>
            <content>Voici quelques exemples de noms propres modifiés par des propositions relatives comprises dans des phrases simples mais complètes :</content>
        </p>
        <example>
            <interlinear exampleLoc="prop/relClExample"/>
        </example>
    </section1>
   <showWhen id="swClassifiersYesPropYes">
	  <whenValue element="typology"  attr="classifier" value="yesAgr"/>
	  <and/>
	  <whenValue element="prop" attr="pnClassifier" value="yes"/>
   </showWhen>
   <showWhen id="swClassifiersYesPropNo">
	  <whenValue element="typology"  attr="classifier" value="yesAgr"/>
	  <and/>
	  <whenValue element="prop" attr="pnClassifier" value="no"/>
   </showWhen>
   <showWhen id="swNPArtAndDemNotNo">
	  <whenValue element="np" attr="artAndDem" value="no" negateValue="yes"/>
   </showWhen>
</portion>

=== sillsdev/paws/resources/configuration/XMLWriterPracticalFrenchDescriptions/WriterFrPracticalAdvCl.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE portion SYSTEM "..\Data\PAWSSKWriterDescription.dtd">
<portion>
    <section1 id="sAdvCl">
        <secTitle>Propositions adverbiales</secTitle>
        <p>
            <content>Cette section considère les compléments qui peuvent suivre les adverbes de temps et de raison, que nous avons présentés à la section </content>
            <sectionRef sec="sAdvPTemporal"/>
            <content> et à la section </content>
            <sectionRef sec="sAdvPReason"/>
            <content>.  Toutes ces propositions adverbiales fonctionnent de la même façon que les adverbes simples; on les traitera comme des syntagmes adverbiaux complétifs de type approprié. Les propositions adverbiales peuvent normalement se mettre en position initiale ou finale</content>
        </p>
        <section2 id="sAdvClTemporal">
            <secTitle>Les compléments d’adverbes temporels</secTitle>
            <p contentType="ctComparativeIntro">
                <content>Des exemples en français d’adverbes temporels avec compléments utilisés dans des phrases complètes: </content><langData>[Depuis ce temps là], Jean est de mauvaise humeur</langData><content>; </content>
                <langData>Jean est à la maison  [depuis la semaine dernière]</langData><content>; </content><langData>[Depuis que Jean est rentré de l’hôpital], il se porte mieux</langData><content>; </content>
                <langData>Jean se sent bien  [maintenant qu’il est rentré de l’hôpital]</langData><content>; </content><langData>Le chien a suivi Suzanne partout  [depuis qu’elle est revenue de l’université]</langData>
                <content> et </content><langData>[Quand elle est revenue de l’université], le chien a suivi Suzanne partout</langData><content>. Ces exemples montrent que certains adverbes temporels admettent certains types de compléments. Par exemple, </content>
                <langData>depuis</langData>
                <content> peut être suivi d’un deuxième adverbe temporel ou bien d’un syntagme nominal temporel, ou bien il peut avoir un complément à proposition finie, avec complémentiseur.  L’adverbe temporel </content>
                <langData>quand</langData>
                <content> prend un complément sententiel fini; par contre </content>
                <langData>maintenant</langData>
                <content> prend un complément à proposition finie, avec complémentiseur.</content>
            </p>
            <p>
                <content>En </content>
                <langName/>
                <content>, les adverbes temporels admettent les compléments semblables à ceux qu’on a cités à la section </content>
               <sectionRef sec="sComp"/>
                <content>.  Les compléments se mettent </content>
                <case element="advcl" attr="advOrNPPos">
                    <caseText value="before">avant</caseText>
                    <caseText value="after">après</caseText>
                    <caseText value="either">d’un côté ou de l’autre de</caseText>
                    <caseText value="unknown">_______</caseText>
                </case>
                <content> l’adverbe temporel. Voici des exemples de propositions adverbiales de temps qui figurent dans les phrases complètes: </content>
            </p>
            <example>
                <interlinear exampleLoc="advcl/tempSentExample"/>
            </example>
        </section2>
        <section2 id="sAdvClReason">
            <secTitle>Les compléments d’adverbes de raison</secTitle>
            <p contentType="ctComparativeIntro">
                <content>Les syntagmes adverbiaux ou les propositions adverbiales qui expriment la raison ou le but consistent d’adverbes autonomes comme </content>
                <langData>donc</langData>
                <content> (qu’on appelle quelquefois les conjonctions sententielles), et de ceux qui prennent une variété de propositions complétives.  Voici des exemples en anglais et français d’adverbes de raison ou de but qui prennent des propositions complétives: </content>
                <langData>John rushed to the hospital [because Sue was in an accident]</langData><gloss><content>  « Jean est allé vite à l’hôpital [parce que Suzanne était dans un accident] »</content></gloss><content>; </content>
                <langData>[Since Jill said that she likes him], Joe smiles all the time</langData><gloss><content>  « [Puisque Jeanne a dit qu’elle l’aime] Jacques sourit tout le temps »</content></gloss>
                <content>; </content><langData>Bill rushed to the airport [so that he could see Kay before she left]</langData><gloss><content>  « Guillaume est allé vite à l’aéroport [pour qu’il puisse voir Gaby avant qu’elle soit partie] »</content></gloss><content>; </content>
                <langData>The troops threw grenades at the enemy [in order to escape]</langData><gloss><content>  « Les soldats ont lancé des grenades à l’ennemi [pour qu’il puissent s’évader] »</content></gloss>
                <content> et </content><langData>The troops threw grenades at the enemy [in order for the prisoners to escape]</langData><gloss><content>  « Les soldats ont lancé des grenades à l’ennemi [pour que les prisonniers puissent s’évader] »</content></gloss>
                <content>.  Dans ces examples en anglais, </content>
                <langData>because</langData><gloss><content> « parce que »</content></gloss>
                <content> et </content>
                <langData>since</langData><gloss><content> « puisque »</content></gloss>
                <content> prennent seulement des complements phrastiques finis et </content>
                <langData>so</langData><gloss><content> « donc, pour »</content></gloss>
                <content> prend une proposition finie avec un complémentiseur comme complément. Par contre </content>
                <langData>in order</langData><gloss><content> « pour »</content></gloss>
                <content> prend ou un complément phrastique non-fini avec un sujet coréférentiel nul, ou bien une proposition non-fini avec un complémentiseur comme complément. Ceci est pareil à la sous-catégorie représentée par </content>
                <langData>like</langData><gloss><content> « aimer »</content></gloss>
                <content> et </content>
                <langData>hate</langData><gloss><content> « haïr »</content></gloss>
                <content> à la section </content>
                <sectionRef sec="sComp"/>
                <content>.</content>
            </p>
           <p contentType="ctPracticalIntro">
               <content>Les syntagmes adverbiaux ou les propositions adverbiales qui expriment la raison ou le but consistent d’adverbes autonomes, comme </content>
              <langData>donc</langData>
               <content> (qu’on appelle quelquefois les conjonctions sententielles), et de ceux qui prennent une variété de propositions complétives pareilles à celles qu’on a citées pour les verbes à la section </content>
              <sectionRef sec="sComp"/>
              <content>.</content>
           </p>
           <p>
               <content>Voici des exemples en </content>
                <langName/>
               <content> de propositions adverbiales de raison ou de but dans des phrases complètes:</content>
            </p>
            <example>
                <interlinear exampleLoc="advp/reasonExample"/>
            </example>
        </section2>
    </section1>
</portion>

=== sillsdev/paws/src/org/sil/paws/resources/configuration/XMLWriterPracticalSpanishDescriptions/WriterSpPracticalProp.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE portion SYSTEM "..\Data\PAWSSKWriterDescription.dtd">
<portion>
    <section1 id="sProp">
        <secTitle>Los nombres propios</secTitle>
       <p contentType="ctPracticalIntro">
          <content>Los nombres propios son una clase especial de sustantivos o frases que sintácticamente funcionan igual que otros sustantivos o frases nominales.</content>
          </p>
          <p contentType="ctComparativeIntro">
            <content>Los nombres propios son una clase especial de sustantivos o frases que sintácticamente funcionan igual que otros sustantivos o frases nominales. En español, algunos nombres propios pueden presentarse solos, como </content>
            <langData>Susana</langData>
            <content> y </content>
            <langData>Oaxaca</langData>
            <content>.  Otros funcionan como sustantivos compuestos, como </content>
            <langData>George Washington</langData>
             <content>.  Los nombres propios también pueden contener los artículos y/o frases </content>
            <case element="pp" attr="pPos">
                <caseText value="before">preposicionales</caseText>
                <caseText value="after">posposicionales</caseText>
                <caseText value="both">adposicionales</caseText>
                <caseText value="unknown">adposicionales</caseText>
            </case>
            <content>, como en </content>
            <langData>los Estados Unidos de América</langData>
            <content>.  Muchas lenguas requieren un artículo antes de un nombre. También se presentan los apositivos.  En algunos casos aparecen con un posesivo, como en </content>
            <langData>mi hijo, David</langData>
             <content>, pero apositivos se tratann más adelante en la sección </content><sectionRef sec="sCoordAppositive"/><content>.  Además, los nombres propios se pueden modificar con los adjetivos y cláusulas relativas, como en </content>
            <langData>México fuerte y orgulloso</langData>
            <content> o </content>
            <langData>la Susana que conozco</langData>
            <content>.</content>
        </p>
       <p show="swClassifiersYesPropYes"><content>En el </content><langName/><content>, los nombres propios se marcan con clasificadores lo mismo que sustantivos como parte del sistema de concordancia.</content></p> 
       <p show="swClassifiersYesPropNo"><content>En el </content><langName/><content>, los nombres propios no se marcan con clasificadores al contrario que sustantivos.</content></p>       
       <p show="swNPArtAndDemNotNo"><content>Los nombres propios</content><case element="prop" attr="pnDeterminer">
          <caseText value="none"> no pueden</caseText>
           <caseText value="no"> pueden</caseText>
           <caseText value="yes"> deben</caseText>
       </case><content> contener un </content><case element="np" attr="artAndDem">
          <caseText value="article">artículo</caseText>
          <caseText value="demonstrative">demostrativo</caseText>
          <caseText value="both">artículo o demostrativo</caseText></case><content> o un posesivo.</content></p>
        <p>
            <content>Algunos ejemplos de nombres propios simples y compuestos en el </content>
            <langName/>
            <content> son los siguientes:</content>
        </p>
        <example>
            <interlinear exampleLoc="prop/example"/>
        </example>
        <p>
            <content>Algunos ejemplos de nombres propios con frases </content>
            <case element="pp" attr="pPos">
                <caseText value="before">preposicionales</caseText>
                <caseText value="after">posposicionales</caseText>
                <caseText value="both">adposicionales</caseText>
                <caseText value="unknown">adposicionales</caseText>
            </case>
            <content> son los siguientes:</content>
        </p>
        <example>
            <interlinear exampleLoc="prop/ppExample"/>
        </example>
        <p>
            <content>Algunos ejemplos de nombres propios modificados por cláusulas relativas en oraciones completas son:</content>
        </p>
        <example>
            <interlinear exampleLoc="prop/relClExample"/>
        </example>
    </section1>
   <showWhen id="swClassifiersYesPropYes">
      <whenValue element="typology"  attr="classifier" value="yesAgr"/>
      <and/>
      <whenValue element="prop" attr="pnClassifier" value="yes"/>
   </showWhen>
   <showWhen id="swClassifiersYesPropNo">
      <whenValue element="typology"  attr="classifier" value="yesAgr"/>
      <and/>
      <whenValue element="prop" attr="pnClassifier" value="no"/>
   </showWhen>
   <showWhen id="swNPArtAndDemNotNo">
      <whenValue element="np" attr="artAndDem" value="no" negateValue="yes"/>
   </showWhen>
</portion>
