=== sillsdev/paws/src/org/sil/paws/resources/configuration/Data/PAWSSKHtmlMapper.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--DTD generated by XML Spy v3.5 (http://www.xmlspy.com)-->
<!-- DTD for PAWS Starter Kit XML to HTML and code mappers -->
<!ENTITY nbsp "&#160;">
<!ENTITY % embedded "#PCDATA | a | br | category | catMap | contents | example | feature |
						 featureChart | file | help | i | ol | p | section | span |
			 technicalTermRef | template | templateName | tool | tree | u | ul">
<!ENTITY % TechnicalTerms SYSTEM  "PAWSTechnicalTerms.dtd">
%TechnicalTerms; 

<!ELEMENT a (%embedded;)*>
<!ATTLIST a
	href CDATA #REQUIRED
	target CDATA #IMPLIED
>
<!ELEMENT and EMPTY>
<!ELEMENT br EMPTY>
<!ELEMENT button EMPTY>
<!ATTLIST button
	id ID #REQUIRED
	value (Back | Next | Yes | No) #REQUIRED
	goto CDATA #IMPLIED
	gotoNoGrammar CDATA #IMPLIED
	>
<!ELEMENT buttons (button, codeInfo?, ruleInfo?, button, codeInfo?, ruleInfo?)>
<!ELEMENT category (#PCDATA)>
<!-- content is the name of the syntactic category -->
<!ELEMENT catMap (#PCDATA)>
<!ATTLIST catMap
	id ID #REQUIRED
	dataItem CDATA #REQUIRED
>
<!ELEMENT checkbox (#PCDATA | textBox)* >
<!ATTLIST checkbox
	id ID #REQUIRED
	dataItem CDATA #REQUIRED
	checked (yes) #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT checkboxGroup (prompt, checkbox+)>
<!ATTLIST checkboxGroup
	id ID #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT closeParen EMPTY>
<!ELEMENT codeInfo (#PCDATA)>
<!ELEMENT contentCheckBoxOther EMPTY>
<!ATTLIST contentCheckBoxOther
   contentLoc CDATA #REQUIRED
   id ID #IMPLIED
><!ELEMENT contents (#PCDATA)>
<!ELEMENT div (textBox | prompt | radioGroup | instruction | codeInfo | ruleInfo | introduction | EnglishExample | br | div | table)*>
<!ATTLIST div
	id ID #REQUIRED
	show IDREF #REQUIRED
>
<!ELEMENT EnglishExample (exItem+)>
<!ELEMENT example (#PCDATA)>
<!ELEMENT exItem (#PCDATA | span | u | sub)*>
<!ATTLIST exItem
	label CDATA #IMPLIED
>
<!ELEMENT feature (#PCDATA)>
<!ELEMENT featureChart (featureRow)+>
<!ATTLIST featureChart
	types (yes | no) "yes"
	explanations (yes | no) "yes"
>
<!ELEMENT featureExplanation (#PCDATA | technicalTermRef)*>
<!ELEMENT featureItem (#PCDATA | technicalTermRef)*>
<!ATTLIST featureItem
	dataValue CDATA #REQUIRED
	name CDATA #REQUIRED
>
<!ELEMENT featureRow (featureType?, featureItem, featureExplanation, textBox?)+>
<!ATTLIST featureRow
	id ID #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT featureType (#PCDATA)>
<!ATTLIST featureType
	rowspan CDATA #IMPLIED
>
<!ELEMENT file (#PCDATA)>
<!ATTLIST file
	id ID #REQUIRED
	section CDATA #REQUIRED
>
<!--
transparent = 'yes' means do not show yellow background, let the grey background come through.
-->
<!ELEMENT form ((textBox | prompt | radioGroup | checkboxGroup | instruction | codeInfo | ruleInfo | introduction | EnglishExample | table | br | div)*, br?, buttons)>
<!ATTLIST form
	transparent (yes | no) "no"
	section CDATA #REQUIRED
>
<!ELEMENT help (#PCDATA)>
<!ATTLIST help
	href CDATA #REQUIRED
>
<!ELEMENT i (#PCDATA)>
<!ELEMENT groupName (#PCDATA)>
<!ATTLIST groupName
	dataItem CDATA #REQUIRED
	default CDATA #REQUIRED
	position (no | yesSpec | yesHead | yesHeadDiff) "no"
>
<!ELEMENT instruction (%embedded; | codeInfo | ruleInfo)*>
<!ATTLIST instruction
	id ID #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT introduction (%embedded; | codeInfo | ruleInfo)*>
<!ATTLIST introduction
	transparent (yes | no) "yes"
	id ID #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT li (%embedded;)*>
<!ATTLIST li
	id ID #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT not EMPTY>
<!ELEMENT ol (li+)>
<!ELEMENT p (%embedded;)*>
<!ATTLIST p
	style CDATA #IMPLIED
>
<!ELEMENT openParen EMPTY>
<!ELEMENT or EMPTY>
<!ELEMENT page (title, (introduction | EnglishExample | table | instruction)*, form, showWhen*, technicalTerms?)>
<!ATTLIST page
	id ID #REQUIRED
	count CDATA #IMPLIED
>
<!ELEMENT prompt (%embedded;)*>
<!ATTLIST prompt
	id ID #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT radio (%embedded;)*>
<!ATTLIST radio
	id ID #REQUIRED
	dataValue CDATA #REQUIRED
	checked (yes) #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT radioGroup (groupName, prompt, radio, (radio | codeInfo | ruleInfo | radioGroup | checkboxGroup)*)>
<!ATTLIST radioGroup
	id ID #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT ruleInfo (#PCDATA)>
<!ELEMENT span (%embedded;)*>
<!ATTLIST span
	id ID #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT section (#PCDATA)>
<!ATTLIST section
	number CDATA #REQUIRED
>
<!ELEMENT showWhen (openParen*, not?, (whenRadio | whenValue | whenCheckbox), ((or | and), openParen*, not?, (whenRadio | whenValue | whenCheckbox), closeParen*)*, closeParen*)>
<!ATTLIST showWhen
	id ID #REQUIRED
>
<!ELEMENT sub (#PCDATA)>
<!ELEMENT table (tr+) >
<!ATTLIST table
	id ID #IMPLIED
	show IDREF #IMPLIED
	class CDATA #IMPLIED
>
<!ELEMENT td (#PCDATA | contentCheckBoxOther)* >
<!ATTLIST td
	colspan CDATA #IMPLIED
>
<!ELEMENT textBox EMPTY>
<!ATTLIST textBox
	id ID #REQUIRED
	contenteditable (true | inherit | false) "inherit"
	dataItem CDATA #REQUIRED
	section CDATA #IMPLIED
	rows CDATA #IMPLIED
	cols CDATA #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT th (#PCDATA) >
<!ATTLIST th
	colspan CDATA #IMPLIED
>
<!ELEMENT title (#PCDATA | i)*>
<!ATTLIST title
	level CDATA #IMPLIED
>
<!ELEMENT template (#PCDATA)>
<!ELEMENT templateName (#PCDATA)>
<!ELEMENT tool (#PCDATA)>
<!ELEMENT tr (th | td)+ >
<!ATTLIST tr
	id ID #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT tree (#PCDATA | br)*>
<!ATTLIST tree
	img CDATA #IMPLIED
>
<!ELEMENT u (#PCDATA)>
<!ELEMENT ul (li+)>
<!ELEMENT whenCheckbox EMPTY>
<!ATTLIST whenCheckbox
	button IDREF #REQUIRED
>
<!ELEMENT whenRadio EMPTY>
<!ATTLIST whenRadio
	button IDREF #REQUIRED
>
<!ELEMENT whenValue EMPTY>
<!ATTLIST whenValue
	element CDATA #REQUIRED
	attr CDATA #REQUIRED
	value CDATA #REQUIRED
>

=== sillsdev/paws/src/org/sil/paws/resources/configuration/XmlPageDescriptions/QMain_fr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "..\Data\PAWSSKHtmlMapper.dtd">
<?xml-stylesheet type="text/xsl" href="..\Templates\PAWSSKHtmlMapper.xsl"?>
<page id="QMain" count="1/9">
    <title>Questions</title>
    <introduction id="QMainIntroNotPractical" show="swNotPractical">This section considers the main clause and embedded clause varieties of Yes/No questions and content questions.  We will begin with Yes/No questions.
<br/>
        <br/>
 In English, main clause Yes/No questions are formed by moving an auxiliary verb in front of the subject.  Other languages use a Yes/No question marker or special complementizer instead of the fronted auxiliary.  This is the case in embedded Yes/No questions in English: no auxiliary fronting is allowed but <example>whether</example> or <example>if</example> fills the complementizer position.<br/>
        <br/>
As discussed in <section number="10">Complement Clauses</section>, X-bar theory takes the complementizer to be the head of the phrase, so a CP sits on top of the IP for questions even in main clauses.  Sample trees for main clause and embedded Yes/No questions in English are shown here:
<tree img="TreeDescriptions/PawsMainYNQues.png"/>
        <br/>
        <tree img="TreeDescriptions/PawsEmbYNQues.png"/>
        <br/>
        <help href="Help/Cbgbtext.doc#CPYesNoQuestions">Click here for more information about the CP phrase structure of Yes/No questions.</help>
       <br/><br/>Since a language may act differently  in Yes/No questions in the main clause versus subordinate clauses, each type will be discussed in turn.
    </introduction>
    <introduction id="QMainIntroPractical" show="swPractical">Cette section traite les variétés les plus importants de proposition principale et de proposition subordonnée des questions oui/non et des questions de contenu  Nous allons commencer avec les questions oui/non.
        <br/>
        <br/>
        En anglais, la proposition principale des questions oui/non est formée en plaçant un verbe auxiliaire devant le sujet.  En français les questions oui/non se forment ou par l’inversion du verbe et du sujet ou par l’addition de <example>est-ce que/qu’</example> au début de la phrase. D’autres langues utilisent un marqueur de question oui/non ou un complétiviseur spécial au lieu de l’auxiliaire au début de la phrase.  C’est le cas des questions subordonnées oui/non en anglais et en français: aucun auxiliaire o verbe précédent n’est autorisé mais <example>si</example> remplit la position complétiviseur.<br/>
        <br/><br/>Comme une langue peut agir différemment dans les questions oui/non dans la proposition principale par rapport aux propositions subordonnées, chaque type sera discuté à son tour.
    </introduction>
    <form section="q" transparent="yes">
        <br/>
        <buttons>
            <button id="QMainBack" value="Back" goto="Contents.htm"/>
            <button id="QMainNext" value="Next" goto="QMainYN.xml"/>
        </buttons>
    </form>
    <showWhen id="swNotPractical">
        <whenValue  element="paws" attr="outputGrammar" value="True"/>
    </showWhen>
    <showWhen id="swPractical">
        <whenValue  element="paws" attr="outputGrammar" value="False"/>
    </showWhen>
</page>

=== sillsdev/paws/src/org/sil/paws/resources/configuration/XmlPageDescriptions/PronTesting_es.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "../Data/PAWSSKHtmlMapper.dtd">
<?xml-stylesheet type="text/xsl" href="..\Templates\PAWSSKHtmlMapper.xsl"?>
<page id="PronTesting" count="7.9">
	<title level="2">Pronouns - Testing</title>
	<form section="pron">
		<instruction>To test what you have done so far, save your work now.  This will generate the test file and grammar rules file created to this point.
			<p>
			Process the text file <file id="AdjPTestingFile" section="AdjP">xxxAdjPTest.txt</file> per the instructions on the 
				<a onclick="pawsApp.launchWebPage('Q/HTMs/FLExSetupBrowser.htm')" href="">FLEx setup</a> page or the
				<a onclick="pawsApp.launchWebPage('Q/HTMs/CarlaStudioSetupBrowser.htm')" href="">CARLAStudio setup</a> page, depending on which you are using.</p>
			<p>If any words fail to be parsed by your morphological parser, then the syntactic parser cannot parse any phrases or sentences those words are included in, 
				so you need to fix the problem with the morphlogical parser first.</p>
			<p>You may also find you need to change your answers on the previous pages of PAWS about the order of elements in the phrase structure rules.
			Or you may need to use the Category Mapper on the previous page to correct differences between your categories and those used by PAWS.  
			Make the changes as needed.</p>
			<p>If you have changed anything on the pages within PAWS, you will need to return to this page and then save the files again.  
				Rerun the parsers and check the results again.</p> 
			<p>Please check off this section now in ‘Contents’ and then proceed to
				<section number="8">Adpositional Phrases</section> when you are ready.</p>
		</instruction>
		<br/>
		<buttons>
			<button id="PronTestingBack" value="Back" goto="PronCatMap.xml"/>
			<button id="PronTestingNext" value="Next" goto="Contents_es.htm"/>
		</buttons>
	</form>
</page>

=== sillsdev/paws/src/org/sil/paws/resources/configuration/XmlPageDescriptions/CompTesting.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "..\Data\PAWSSKHtmlMapper.dtd">
<?xml-stylesheet type="text/xsl" href="..\Templates\PAWSSKHtmlMapper.xsl"?>
<page id="CompTesting" count="4/4">
	<title level="2">Complement Clauses - Testing</title>
	<form section="comp">
		<instruction>
To test what you have done so far, save your work now.  This will generate the test file and grammar rules file created to this point.
	<br/>
	<br/>
Run the file <file id="CompTestingFile" section="comp">xxxCompTest.txt</file> through your morphological parser and then
run the syntactic parser on the output (all possible within CarlaStudio, as noted on the ‘Contents’ page).  Check the log for the
results and note any changes you need to make, most likely by adding features to particular entries in the lexicon.  If any words fail to be parsed by your morphological parser, then the syntactic parser cannot parse any phrases or sentences those words are included in, so you need to fix the problem with the morphlogical parser first.  You may also find you need to change your answers on the previous pages of PAWS about the order of elements in the phrase structure rules.   Make the changes as needed.  If you have changed anything on the pages within PAWS, you will need to return to this page and then save the files again.  Rerun the parsers and check the results again.
			<br/>
			<br/>
Please check off this section now in ‘Contents’ and then proceed to
<section number="11">Questions</section> when you are ready.
</instruction>
	<br/>
		<br/>
		<buttons>
			<button id="CompTestingBack" value="Back" goto="CompPosition.xml"/>
			<button id="CompTestingNext" value="Next" goto="Contents.htm"/>
		</buttons>
	</form>
</page>

=== sillsdev/paws/resources/configuration/XmlPageDescriptions/AdvClFeatures_fr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "..\Data\PAWSSKHtmlMapper.dtd" [
<!ENTITY TechnicalTerms SYSTEM  "TechnicalTerms_fr.xml">
]>
<?xml-stylesheet type="text/xsl" href="..\Transforms\PAWSSKHtmlMapper.xsl"?>
<page id="AdvClFeatures" count="13.2">
    <title level="2">Propositions adverbiales – Exemples et Caractéristiques</title>
    <introduction>Nous répétons les exemples d’adverbes temporels avec compléments utilisés dans des phrases complètes cités à la page précédente : </introduction>
   <EnglishExample>
        <exItem label="1.">[Since then], John has been moody.  « [Depuis lors], Jean est de mauvaise humeur. »</exItem>
        <exItem label="2.">John has been home [since last week].  « Jean est à la maison  [depuis la semaine dernière]. »</exItem>
        <exItem label="3.">[Since John has been home from the hospital] he is doing better.  « [Depuis que Jean est rentré de l’hôpital], il se porte mieux. »</exItem>
        <exItem label="4.">John is feeling fine [now that he is home from the hospital].  « Jean se sent bien [maintenant qu’il est rentré de l’hôpital]. »</exItem>
        <exItem label="5.">The dog followed Sue everywhere [when she returned from college].  « Le chien a suivi Suzanne partout  [depuis qu’elle est revenue de l’université]. »</exItem>
        <exItem label="6.">[When she returned from college], the dog followed Sue everywhere.  « [Quand elle est revenue de l’université], le chien a suivi Suzanne partout. »</exItem>
   </EnglishExample>
    <form section="advcl">
        <prompt><br/>Saisissez ici, dans votre langue, des exemples similaires dans lesquelles les propositions adverbiales temporelles sont inclues dans des phrases complètes (simples) :</prompt>
        <textBox id="AdvlClTemporalExample" dataItem="tempSentExample" cols="80"/>
        <br/>
        <radioGroup>
            <groupName dataItem="advOrNPPos" default="unknown" position="yesHeadDiff">RAdvOrNPPos</groupName>
            <prompt>Où se place le complément par rapport à l’adverbe principal, que le complément soit un syntagme adverbial ou nominal, ou un complément de la phrase ou de la proposition ?</prompt>
            <radio id="AdvClAdvOrNPPosBefore" dataValue="before">Avant l’adverbe</radio>
            <radio id="AdvClAdvOrNPPosAfter" dataValue="after">Après l’adverbe</radio>
            <radio id="AdvClAdvOrNPPosEither" dataValue="either">D’un côté ou de l’autre</radio>
        </radioGroup>
        <br/>
        <instruction id="AdvClTemporalInstruction">In the lexicon, add the following features to the adverb entry, in addition to the feature <feature>temporal</feature>.  Note that the first two features can be added to the same entry, and either or both can be added to the other sets of features.
            <ul>
                <li>If the adverb may have another adverb as its complement, add the feature <feature>takes_Adv</feature>.</li>
                <li>If the adverb may have a nominal phrase complement, add the feature <feature>takes_DP</feature>.</li>
                <li>If the adverb may have an IP complement, add the features <feature>sentential_finite_IP</feature>.</li>
                <li id="CompYesOption" show="swCompYes">If the adverb requires a complementizer to be present in its sentential complement (CP), add the feature <feature>sentential_finite_CP</feature> instead.</li>
            </ul>
        </instruction>
        <br/>
        <introduction>En ce qui concerne les syntagmes ou les propositions adverbiaux qui expriment la raison ou le but, nous trouvons des adverbes indépendants, comme <example>therefore/so « ainsi »</example> tout comme des adverbes qui admettent une variété de propositions complément. (Les cas comme <example>for this reason « pour cette raison »</example> devraient fonctionner, sur la base des réponses données dans la section <section number="8">Syntagmes adpositionnels</section>.)
            <br/><br/> Les exemples d’adverbes de raison ou de but qui se construisent avec une proposition complément sont placés [entre crochets] dans les exemples 7-11 :
</introduction>
        <EnglishExample>
            <exItem label="7.">John rushed to the hospital [because Sue was in an accident].   « Jean est allé vite à l’hôpital [parce que Suzanne était dans un accident]. »</exItem>
            <exItem label="8.">[Since Jill said that she likes him], Joe smiles all the time.   « [Puisque Jeanne a dit qu’elle l’aime] Jacques sourit tout le temps. »</exItem>
            <exItem label="9.">Bill rushed to the airport [so that he could see Kay before she left].   « Guillaume est allé vite à l’aéroport [pour qu’il puisse voir Gaby avant qu’elle soit partie]. »</exItem>
            <exItem label="10.">The troops threw grenades at the enemy [in order to escape].   « Les soldats ont lancé des grenades sur l’ennemi [pour qu’ils puissent s’échapper]. »</exItem>
            <exItem label="11.">The troops threw grenades at the enemy [in order for the prisoners to escape].   « Les soldats ont lancé des grenades sur l’ennemi [pour que les prisonniers puissent s’évader]. »</exItem>
        </EnglishExample>
       <instruction id="AdvClReasonIntroNotPractical" show="swNotPractical">In the examples above, <example>because</example> and <example>since</example> take only <technicalTermRef term="ttFinite"/> IP complements and <example>so</example> takes a finite CP complement.  In contrast, <example>in order</example> takes either a <technicalTermRef term="ttNonfinite"/> IP with a subject which is not expressed or a nonfinite CP complement.  This is the same subcategorization as shown for <example>like</example> and <example>hate</example> in <section number="10">Complement Clauses</section>. 
 </instruction>
        <introduction id="AdvClReasonIntroPractical" show="swPractical">Dans les exemples ci-dessus, <example>because « parce que »</example> et <example>since « puisque »</example> prennent seulement des complements phrastiques <technicalTermRef term="ttFinite">finis</technicalTermRef> et <example>so « donc »</example> prend une proposition complétive finie avec un complémentiseur. Par contre <example>pour « in order »</example> prend ou un complément phrastique <technicalTermRef term="ttNonfinite">non-fini</technicalTermRef> avec un sujet coréférentiel nul, ou bien une proposition complétive non-fini avec une conjonction de subordination. Ceci est pareil à la sous-catégorie représentée par <example>like « aimer »</example> et <example>hate « haïr »</example> à la <section number="10">Propositions complétives</section>. 
         </introduction>
        <br/>
        <prompt>Les exemples que vous avez donnés à la <section number="3">Adverbes et Syntagmes adverbiaux</section> sont repris ci-dessous.  Vous pouvez ajouter d’autres exemples sous forme de phrases (simple) complètes.<span id="CompNoSpan" show="swCompNo">  Puisque votre langue n’a pas de conjonctions pour les propositions subordonnées, tous vos exemples ne devraient contenir qu’un complément phrastique.</span></prompt>
        <textBox id="AdvPReasonSentExample" section="advp" dataItem="reasonSentExample" cols="80"/>
        <br/>
        <br/>
        <instruction id="AdvClReasonInstruction">In the lexicon, add the following features to the adverb entry, in addition to the feature <feature>reason</feature>.
            <ul>
                <li>If the adverb may have a finite IP complement, add the feature <feature>sentential_finite_IP</feature>.</li>
                <li id="CompYesOptionReason" show="swCompYes">If the adverb requires a complementizer to be present in its finite sentential complement (CP), add the feature <feature>sentential_finite_CP</feature>.</li>
                <li id="CompYesOptionReason1" show="swCompYes">If the adverb requires either a nonfinite IP with a pro-dropped subject or a nonfinite CP complement (like <example>in order</example> above), add the feature <feature>sentential_-finite</feature>.</li>
            </ul>
            Those that are phrases, like <example>in order</example>, need to be entered in the lexicon as units.  In <tool>FLEx</tool> interlinear, you can link the words together.
            For <tool>CARLAStudio</tool>, use underscores between the words so <tool>Join Compound</tool> will parse them as a single lexical entry within <tool>CARLAStudio</tool>.
        </instruction>
        <br/>
        <buttons>
            <button id="AdvClFeaturesBack" value="Back" goto="AdvClMain.xml"/>
            <button id="AdvClFeaturesNext" value="Next" goto="AdvClTesting.xml" gotoNoGrammar="Contents_fr.htm"/>
        </buttons>
    </form>
   <showWhen id="swCompYes">
      <whenValue element="comp" attr="comp" value="yes"/>
   </showWhen>
   <showWhen id="swCompNo">
      <whenValue element="comp" attr="comp" value="no"/>
   </showWhen>
   <showWhen id="swNotPractical">
        <whenValue  element="paws" attr="outputGrammar" value="True"/>
    </showWhen>
    <showWhen id="swPractical">
        <whenValue  element="paws" attr="outputGrammar" value="False"/>
    </showWhen>
   &TechnicalTerms; 
</page>

=== sillsdev/paws/src/org/sil/paws/resources/configuration/XmlPageDescriptions/IPCatMap.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v3.5 (http://www.xmlspy.com) by Andy Black (SIL International) -->
<!DOCTYPE page SYSTEM "..\Data\PAWSSKHtmlMapper.dtd">
<?xml-stylesheet type="text/xsl" href="..\Templates\PAWSSKHtmlMapper.xsl"?>
<page id="IPCatMap" count="1/1">
	<title level="2">Basic Sentences - Category Mapper</title>
	<form section="ip">
		<instruction id="IPAuxYesInstruction" show="swAuxYes">The auxiliary elements need to have the category <category>Aux</category>.  If a particular form can also stand alone as the main verb in the sentence, you need to have two separate entries, one with the category <category>Aux</category> and one with the category <category>V</category>.  Choose one of the following options, depending on your situation:
<ul>
				<li>If you already have auxiliaries marked with the category <category>Aux</category> in your lexicon nothing more needs to be done.</li>
				<li>If auxiliaries are mixed in with another category in the lexicon, you either need to give them the category <category>Aux</category> in your morphological parser, or add the feature <feature>makeAux</feature> to each appropriate entry in the lexicon so the category will be changed for the syntax.  (If a particular entry can also be used as another syntactic category, make a separate lexical entry for each use.)</li>
				<li>If you have auxiliaries marked in your lexicon with a distinct category all their own, but it is different from <category>Aux</category>, enter that category below so PAWS can map your morphological category to <category>Aux</category>.<br/>
					<catMap id="IPAuxCategory" dataItem="auxCategory">Aux</catMap>
				</li>
			</ul>
		</instruction>
		<instruction>You need to make sure the verbs in your lexicon will be mapped to the syntactic category <category>V</category>.  Choose one of the following options, depending on your situation:
<ul>
				<li>If you already have verbs marked with the category <category>V</category> in your lexicon, nothing 
  more needs to be done.</li>
				<li>If verbs are mixed in with another category in the lexicon, you either need to give them the category <category>V</category> in your morphological parser, or add the feature <feature>makeV</feature> to each appropriate entry in the lexicon so the category will be changed for the syntax.  (If a particular entry can also be used as another syntactic category, make a separate lexical entry for each use.)</li>
				<li>If you have verbs marked in your lexicon with a distinct category all their own, but it is different from <category>V</category>, enter that category below so PAWS can map your morphological category to <category>V</category>. <br/>
					<catMap id="IPVerbCategory" dataItem="verbCategory">V</catMap>
				</li>
			</ul>
		</instruction>
		<br/>
		<br/>
		<buttons>
			<button id="IPCatMapBack" value="Back" goto="IPContents.htm"/>
			<button id="IPCatMapNext" value="Next" goto="IPContents.htm"/>
		</buttons>
	</form>
	<showWhen id="swAuxYes">
		<whenValue element="ip" attr="aux" value="yes"/>
	</showWhen>
</page>

=== sillsdev/paws/src/org/sil/paws/resources/configuration/XmlPageDescriptions/QPPartitive_en.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "..\Data\PAWSSKHtmlMapper.dtd" [
<!ENTITY TechnicalTerms SYSTEM  "TechnicalTerms.xml">
]>
<?xml-stylesheet type="text/xsl" href="..\Transforms\PAWSSKHtmlMapper.xsl"?>
<page id="QPPartitive" count="5/7">
	<title level="2">Quantifiers and QP - Partitives</title>
	<introduction>All of the quantifiers, including numbers, can normally occur in <technicalTermRef term="ttPartitive"/> constructions.  These constructions are used to signify that one is talking about just a part of a larger group.  Examples include:
	</introduction>
   <EnglishExample>
      <exItem label="1.">some of the children.</exItem>
      <exItem label="2.">several of the older girls.</exItem>
      <exItem label="3.">many of the women.</exItem>
      <exItem label="4.">just this much of the food.</exItem>
      <exItem label="5.">only ten of the boys.</exItem>
   </EnglishExample>
   <introduction>As the examples show, partitive constructions of this type normally have a prepositional or postpositional phrase modifying the quantifier, which indicates the group or full item being discussed.  Note that in all of these examples, the noun in the partitive phrase can be further modified by a relative clause.<br/><br/>
      Some languages may use a relative clause to express the group of the partitive construction instead of a prepositional or postpositional phrase.
   </introduction>
	<form section="qp">
	   <prompt><br/>Key how your language would express similar kinds of partitive examples with quantifiers here:</prompt>
	   <textBox id="QPPartitiveQExample" dataItem="partitiveQExample"/>
<br/><br/>
	   <radioGroup>
	      <groupName dataItem="partitive" default="no" >RQPPartitive</groupName>
	      <prompt>Based on the examples you keyed, does your language use prepositional or postpositional phrases in partitive constructions?</prompt>
	      <radio id="QPPartitiveYes" dataValue="yes">Yes</radio>
	      <radio id="QPPartitiveNo" dataValue="no">No, a relative clause is used instead</radio>
	      <radio id="QPPartitiveOther" dataValue="other">No, my language uses some other means than either a prepositional or postpositional phrase or a relative clause to express similar meanings</radio>
	   </radioGroup>
		<prompt id="QPPartitiveOtherPrompt" show="swQPPartitiveOther">The construction my language uses to express the group or item being discussed in this kind of partitive construction is:</prompt>
		<textBox id="QPPartitiveOtherConstruction" dataItem="partitiveConstruction" cols="50" rows="2" show="swQPPartitiveOther"/>
		
	   <radioGroup id="QPPartitivePPPosTable" show="swQPPartitiveYes">
	      <groupName dataItem="partitivePPPos" default="unknown" position="yesHeadDiff">RQPPartitivePPPos</groupName>
	      <prompt>Where does the prepositional or postpositional phrase occur with respect to the quantifier?</prompt>
	      <radio id="QPPartitivePPBefore" checked="yes" dataValue="before">Before the quantifier</radio>
	      <radio id="QPPartitivePPAfter" checked="yes" dataValue="after">After the quantifier</radio>
	      <radio id="QPPartitivePPEitherSide" checked="yes" dataValue="either">On either side</radio>
	   </radioGroup>
	   
	   <prompt id="QPPartitiveOfPrompt" show="swQPPartitiveYes">Key the prepositions or postpositions that can be used to mean “of” in these partitive constructions, with each word on a separate line. </prompt>
	   <textBox id="QPPartitiveOfExample" dataItem="partitiveOf" rows="3" show="swQPPartitiveYes"/>
	   <br/>
	   
	   <prompt id="QPPartitiveRelClPrompt" show="swQPPartitiveNo">The structure of relative clauses will be covered in <section number="12">Relative Clauses</section>.</prompt>
<br/>		<br/>
		<buttons>
			<button id="QPPartitiveBack" value="Back" goto="QPCardinal.xml"/>
		    <button id="QPPartitiveNext" value="Next" goto="QPCatMap.xml" gotoNoGrammar="Contents.htm"/>
		</buttons>
	</form>
   <showWhen id="swQPPartitiveNo">
      <whenRadio button="QPPartitiveNo"/>  
   </showWhen> 
   <showWhen id="swQPPartitiveYes">
      <whenRadio button="QPPartitiveYes"/>  
   </showWhen> 
	<showWhen id="swQPPartitiveOther">
		<whenRadio button="QPPartitiveOther"/>  
	</showWhen> 
	&TechnicalTerms; 
   
</page>
