=== sillsdev/paws/resources/configuration/Data/MasterGrammar.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.3 U (http://www.xmlspy.com) by Andy Black (SIL International) -->
<!--DTD generated by XML Spy v4.3 U (http://www.xmlspy.com)-->
<!ELEMENT and EMPTY>
<!ELEMENT catMapper (#PCDATA)>
<!ATTLIST catMapper
  show IDREF #REQUIRED
>
<!ELEMENT content (#PCDATA)>
<!ELEMENT generalizedTemplates (content | specializedTemplates)*>
<!ELEMENT masterGrammar (rule | generalizedTemplates | specializedTemplates | catMapper | showWhen)*>
<!ELEMENT or EMPTY>
<!ELEMENT rule (#PCDATA)>
<!ATTLIST rule
  show IDREF #IMPLIED
>
<!ELEMENT showWhen ((whenValue | useShowWhen), ((or | and), (whenValue | useShowWhen))*)>
<!ATTLIST showWhen
  id ID #REQUIRED
>
<!ELEMENT specializedTemplates (#PCDATA)>
<!ATTLIST specializedTemplates
  show IDREF #REQUIRED
>
<!ELEMENT whenValue EMPTY>
<!ATTLIST whenValue
  element CDATA #REQUIRED
  attr CDATA #IMPLIED
  value CDATA #REQUIRED
  negateValue (yes | no) "no"
>
<!ELEMENT useShowWhen EMPTY>
<!ATTLIST useShowWhen
  show IDREF #REQUIRED
>
<!--
================================================================
Revision History
- - - - - - - - - - - - - - - - - - -
17-Jul-2002    Andy Black  Allow specializedTemplates to be embedded within generalizedTemplates
02-Jul-2002    Andy Black  Initial version
================================================================
 -->

=== sillsdev/paws/src/org/sil/paws/resources/configuration/XMLGrammarDescriptions/GrammarPP.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE masterGrammar SYSTEM "..\Data\MasterGrammar.dtd">
<masterGrammar>
<rule show="PPoptionconj">
rule {PP option conj - conjoined PPs}
PP = (InitConj) PP_1 Conj PP_2
	&lt;PP head&gt; = &lt;PP_2 head&gt;
	&lt;PP conjoined&gt; = +
	&lt;PP_1 conjoined&gt; = -	|limit recursion
	&lt;PP option&gt; = conj
</rule>
   <showWhen id="PPoptionconj">
      <whenValue element="coord" attr="conjWord" value="no" negateValue="yes"/>
   </showWhen>
   <rule show="PPoptionconjPrefix">
      rule {PP option conjPrefix - conjoined PPs}
      PP = PP_1  PP_2
      &lt;PP head&gt; = &lt;PP_2 head&gt;
      &lt;PP conjoined&gt; = +
      &lt;PP_1 conjoined&gt; = -	|limit recursion
      &lt;PP_2 head type prefix conj&gt; = +
      &lt;PP option&gt; = conjPrefix
   </rule>
   <showWhen id="PPoptionconjPrefix">
      <whenValue element="coord" attr="conjWord" value="yes" negateValue="yes"/>
      <and/>
      <whenValue element="coord/proclitic" attr="checked" value="yes"/>
   </showWhen>
   <rule show="PPoptionconjSuffix">
      rule {PP option conjSuffix - conjoined PPs}
      PP = PP_1  PP_2
      &lt;PP head&gt; = &lt;PP_2 head&gt;
      &lt;PP conjoined&gt; = +
      &lt;PP_1 conjoined&gt; = -	|limit recursion
      &lt;PP_1 head type suffix conj&gt; = +
      &lt;PP option&gt; = conjSuffix
   </rule>
   <showWhen id="PPoptionconjSuffix">
      <whenValue element="coord" attr="conjWord" value="yes" negateValue="yes"/>
      <and/>
      <whenValue element="coord/enclitic" attr="checked" value="yes"/>
   </showWhen>
   <rule show="PPoptionconjNone">
      rule {PP option conjNone - conjoined PPs}
      PP = PP_1  PP_2
      &lt;PP head&gt; = &lt;PP_2 head&gt;
      &lt;PP conjoined&gt; = +
      &lt;PP_1 conjoined&gt; = -	|limit recursion
      &lt;PP_2 head type prefix conj&gt; = -
      &lt;PP_1 head type suffix conj&gt; = -
      &lt;PP_1 head type comma&gt; = -
      &lt;PP option&gt; = conjNone
   </rule>
   <showWhen id="PPoptionconjNone">
      <whenValue element="coord" attr="conjWord" value="yes" negateValue="yes"/>
       <and/>
       <whenValue element="coord/attachesOther" attr="checked" value="yes"/>
       <or/>
       <whenValue element="coord" attr="noConj" value="yes" negateValue="no"/>
   </showWhen>
   <rule>
rule {PP option 0 - no modifiers}
PP = P'
	&lt;PP head&gt; = &lt;P' head&gt;
	&lt;PP option&gt; = 0
</rule>
    <rule show="PPoption1a">
rule {PP option 1a - degree word before}
PP = Deg P'
	&lt;PP head&gt; = &lt;P' head&gt;
	&lt;Deg head type modifies_PP&gt; = +
	&lt;Deg head type PP-initial&gt; = +
	&lt;Deg head type comma&gt; = -
	&lt;PP option&gt; = 1a
</rule>
    <showWhen id="PPoption1a">
        <whenValue element="pp" attr="modifiers" value="yes" negateValue="no"/>
        <and/>
        <whenValue element="pp/ppModifierDegree" attr="checked" value="yes"/>
        <and/>
        <whenValue element="pp/ppDegreePosBefore" attr="checked" value="yes"/>
    </showWhen>
    <rule show="PPoption1b">
rule {PP option 1b - degree word after}
PP = P' Deg
	&lt;PP head&gt; = &lt;P' head&gt;
	&lt;Deg head type modifies_PP&gt; = +
	&lt;Deg head type PP-final&gt; = +
	&lt;P' head type comma&gt; = -
	&lt;PP head type comma&gt; &lt;= &lt;Deg head type comma&gt;
	&lt;PP option&gt; = 1b
</rule>
    <showWhen id="PPoption1b">
        <whenValue element="pp" attr="modifiers" value="yes" negateValue="no"/>
        <and/>
        <whenValue element="pp/ppModifierDegree" attr="checked" value="yes"/>
        <and/>
        <whenValue element="pp/ppDegreePosAfter" attr="checked" value="yes"/>
    </showWhen>
    <rule show="PPoption1c">
rule {PP option 1c - degree word both sides}
PP = Deg_1 P' Deg_2
	&lt;PP head&gt; = &lt;P' head&gt;
	&lt;Deg_1 head type modifies_PP&gt; = +
	&lt;Deg_1 head type PP-initial&gt; = +
	&lt;Deg_2 head type modifies_PP&gt; = +
	&lt;Deg_2 head type PP-final&gt; = +
	&lt;Deg_1 head type comma&gt; = -
	&lt;P' head type comma&gt; = -
	&lt;PP head type comma&gt; &lt;= &lt;Deg_2 head type comma&gt;
	&lt;PP option&gt; = 1c
</rule>
    <showWhen id="PPoption1c">
        <whenValue element="pp" attr="modifiers" value="yes" negateValue="no"/>
        <and/>
        <whenValue element="pp/ppModifierDegree" attr="checked" value="yes"/>
        <and/>
        <whenValue element="pp/ppDegreePosBoth" attr="checked" value="yes"/>
    </showWhen>
    <rule show="PPoption2a">
rule {PP option 2a - adverbial before}
PP = AdvP P'
	&lt;PP head&gt; = &lt;P' head&gt;
	&lt;AdvP head type manner&gt; = +
	&lt;AdvP head type PP-initial&gt; = +
	&lt;AdvP head type comma&gt; = -
	&lt;PP option&gt; = 2a
</rule>
    <showWhen id="PPoption2a">
        <whenValue element="pp" attr="modifiers" value="yes" negateValue="no"/>
        <and/>
        <whenValue element="pp/ppModifierManner" attr="checked" value="yes"/>
        <and/>
        <whenValue element="pp/ppMannerPosBefore" attr="checked" value="yes"/>
    </showWhen>
    <rule show="PPoption2b">
rule {PP option 2b - adverbial after}
PP = P' AdvP
	&lt;PP head&gt; = &lt;P' head&gt;
	&lt;AdvP head type manner&gt; = +
	&lt;AdvP head type PP-final&gt; = +
	&lt;P' head type comma&gt; = -
	&lt;PP head type comma&gt; &lt;= &lt;AdvP head type comma&gt;
	&lt;PP option&gt; = 2b
</rule>
    <showWhen id="PPoption2b">
        <whenValue element="pp" attr="modifiers" value="yes" negateValue="no"/>
        <and/>
        <whenValue element="pp/ppModifierManner" attr="checked" value="yes"/>
        <and/>
        <whenValue element="pp/ppMannerPosAfter" attr="checked" value="yes"/>
    </showWhen>
    <rule show="PPoption2c">
rule {PP option 2c - adverbial both sides}
PP = AdvP_1 P' AdvP_2
	&lt;PP head&gt; = &lt;P' head&gt;
	&lt;AdvP_1 head type manner&gt; = +
	&lt;AdvP_1 head type PP-initial&gt; = +
	&lt;AdvP_2 head type manner&gt; = +
	&lt;AdvP_2 head type PP-final&gt; = +
	&lt;AdvP_1 head type comma&gt; = -
	&lt;P' head type comma&gt; = -
	&lt;PP head type comma&gt; &lt;= &lt;AdvP_2 head type comma&gt;
	&lt;PP option&gt; = 2c
</rule>
    <showWhen id="PPoption2c">
        <whenValue element="pp" attr="modifiers" value="yes" negateValue="no"/>
        <and/>
        <whenValue element="pp/ppModifierManner" attr="checked" value="yes"/>
        <and/>
        <whenValue element="pp/ppMannerPosBoth" attr="checked" value="yes"/>
    </showWhen>
     <rule show="PPoption2aLoc">
rule {PP option 2aLoc - locative adverbial before}
PP = AdvP P'
	&lt;PP head&gt; = &lt;P' head&gt;
	&lt;AdvP head type locative&gt; = +
	&lt;AdvP head type PP-initial&gt; = +
	&lt;AdvP head type comma&gt; = -
	&lt;PP option&gt; = 2aLoc
</rule>
    <showWhen id="PPoption2aLoc">
        <whenValue element="pp" attr="modifiers" value="yes" negateValue="no"/>
        <and/>
        <whenValue element="pp/ppModifierLocative" attr="checked" value="yes"/>
        <and/>
        <whenValue element="pp/ppLocativePosBefore" attr="checked" value="yes"/>
    </showWhen>
    <rule show="PPoption2bLoc">
rule {PP option 2bLoc - locativeadverbial after}
PP = P' AdvP
	&lt;PP head&gt; = &lt;P' head&gt;
	&lt;AdvP head type locative&gt; = +
	&lt;AdvP head type PP-final&gt; = +
	&lt;P' head type comma&gt; = -
	&lt;PP head type comma&gt; &lt;= &lt;AdvP head type comma&gt;
	&lt;PP option&gt; = 2bLoc
</rule>
    <showWhen id="PPoption2bLoc">
        <whenValue element="pp" attr="modifiers" value="yes" negateValue="no"/>
        <and/>
        <whenValue element="pp/ppModifierLocative" attr="checked" value="yes"/>
        <and/>
        <whenValue element="pp/ppLocativePosAfter" attr="checked" value="yes"/>
    </showWhen>
    <rule show="PPoption2cLoc">
rule {PP option 2cLoc - locative adverbial both sides}
PP = AdvP_1 P' AdvP_2
	&lt;PP head&gt; = &lt;P' head&gt;
	&lt;AdvP_1 head type locative&gt; = +
	&lt;AdvP_1 head type PP-initial&gt; = +
	&lt;AdvP_2 head type manner&gt; = +
	&lt;AdvP_2 head type PP-final&gt; = +
	&lt;AdvP_1 head type comma&gt; = -
	&lt;P' head type comma&gt; = -
	&lt;PP head type comma&gt; &lt;= &lt;AdvP_2 head type comma&gt;
	&lt;PP option&gt; = 2cLoc
</rule>
    <showWhen id="PPoption2cLoc">
        <whenValue element="pp" attr="modifiers" value="yes" negateValue="no"/>
        <and/>
        <whenValue element="pp/ppModifierLocative" attr="checked" value="yes"/>
        <and/>
        <whenValue element="pp/ppLocativePosBoth" attr="checked" value="yes"/>
    </showWhen>
    <rule show="PPoption3a">
rule {PP option 3a - ordinal before}
PP = AdjP P'
	&lt;PP head&gt; = &lt;P' head&gt;
	&lt;AdjP head type ordinal&gt; = +
	&lt;AdjP head type PP-initial&gt; = +
	&lt;AdjP head type comma&gt; = -
	&lt;PP option&gt; = 3a
</rule>
    <showWhen id="PPoption3a">
        <whenValue element="pp" attr="modifiers" value="yes" negateValue="no"/>
        <and/>
        <whenValue element="pp/ppModifierOrdinal" attr="checked" value="yes"/>
        <and/>
        <whenValue element="pp/ppOrdinalPosBefore" attr="checked" value="yes"/>
    </showWhen>
    <rule show="PPoption3b">
rule {PP option 3b - ordinal after}
PP = P' AdjP
	&lt;PP head&gt; = &lt;P' head&gt;
	&lt;AdjP head type ordinal&gt; = +
	&lt;AdjP head type PP-final&gt; = +
	&lt;P' head type comma&gt; = -
	&lt;PP head type comma&gt; &lt;= &lt;AdjP head type comma&gt;
	&lt;PP option&gt; = 3b
</rule>
    <showWhen id="PPoption3b">
        <whenValue element="pp" attr="modifiers" value="yes" negateValue="no"/>
        <and/>
        <whenValue element="pp/ppModifierOrdinal" attr="checked" value="yes"/>
        <and/>
        <whenValue element="pp/ppOrdinalPosAfter" attr="checked" value="yes"/>
    </showWhen>
    <rule show="PPoption3c">
rule {PP option 3c - ordinal both sides}
PP = AdjP_1 P' AdjP_2
	&lt;PP head&gt; = &lt;P' head&gt;
	&lt;AdjP_1 head type ordinal&gt; = +
	&lt;AdjP_1 head type PP-initial&gt; = +
	&lt;AdjP_2 head type ordinal&gt; = +
	&lt;AdjP_2 head type PP-final&gt; = +
	&lt;AdjP_1 head type comma&gt; = -
	&lt;P' head type comma&gt; = -
	&lt;PP head type comma&gt; &lt;= &lt;AdjP_2 head type comma&gt;
